### ISSUE TITLE
Interview  problem

### ISSUE THREAD

**Issue by boronkayp** [hassio-addons/addon-zwavejs2mqtt#100]
# Problem/Motivation

After restart the non-battery powered devices can not be interviewed.    

## Expected behavior

Every device should be interviewed.  

## Actual behavior

Only the battery powered devices show up on the UI. 
So the manufacturer, the product and product code fields are empty, and these devices /and related entities/ are unavailable, on HA side. 

## Steps to reproduce

Restart the add-on.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Add-ons wrap existing software, in this case Z-Wave JS to MQTT. We do no developer the software itself, if you have an issue with the software itself, please report it upstream.

If this is an issue with how it is processed in Home Assistant, please report it with the Home Assistant project. Thanks 👍
