### ISSUE TITLE
Yale YRD110 parameters are being lost

### ISSUE THREAD

**Issue by PrayerfulDrop** [hassio-addons/addon-zwavejs2mqtt#102]
Yale YRD110 Zwave locks are not reporting any additional parameters of the lock event state.  Using an event listener for zwave_js_event and also keymaster_lock_state_changed I see the following information:

zwave_js_event:
{
    "event_type": "zwave_js_event",
    "data": {
        "type": "notification",
        "domain": "zwave_js",
        "node_id": 58,
        "home_id": 4172338759,
        "device_id": "01bb8f2c1b64539cfc8dbf6b1c188f91",
        "label": "RF unlock operation",
        "parameters": {}
    },
    "origin": "LOCAL",
    "time_fired": "2021-03-30T22:08:50.643068+00:00",
    "context": {
        "id": "a8cd0b551a5a6ac98e7f06fc6920f335",
        "parent_id": null,
        "user_id": null
    }
}

keymaster_lock_state_changed:
{
    "event_type": "keymaster_lock_state_changed",
    "data": {
        "notification_source": "entity_state",
        "lockname": "garagedoor",
        "entity_id": "lock.garage_door",
        "state": "locked",
        "action_code": 130,
        "action_text": "Unknown Alarm Type Value",
        "code_slot": 1,
        "code_slot_name": "Aaron"
    },
    "origin": "LOCAL",
    "time_fired": "2021-03-30T22:04:43.730096+00:00",
    "context": {
        "id": "fcc515f6beb3467940f5e77aa4874aff",
        "parent_id": null,
        "user_id": null
    }
}

Do to additional parameters not being captured the "action_text" is left with an unknown value state.

**Comment by frenck** [comment]
This is the add-on, if you have an issue with the Home Assistant integration, please report it with Home Assistant itself. Thanks 👍
