### ISSUE TITLE
Update ZwaveJS2MQTT to ZwaveJS V7.0.1 to fix mapping reports

### ISSUE THREAD

**Issue by DayRunner131** [hassio-addons/addon-zwavejs2mqtt#104]
# Problem/Motivation

> To fix duplicate mapping for ZEN16 Multirelay. See https://github.com/zwave-js/node-zwave-js/issues/1748#issuecomment-811516907

## Expected behavior

> RLY1, RLY2, RLY3 all should map separately in current value on Zen16 Multirelay.

## Actual behavior

> RLY1 duplicates the mapping on RLY2 & RLY3. 

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> Update ZwaveJS to v7.0.1 per issue here: https://github.com/zwave-js/node-zwave-js/pull/2160

**Comment by frenck** [comment]
This is not Z-Wave JS, but Z-Wave JS to MQTT.
Your request does not match the program running in this add-on.

**Comment by DayRunner131** [comment]
> This is not Z-Wave JS, but Z-Wave JS to MQTT.
> Your request does not match the program running in this add-on.



> This is not Z-Wave JS, but Z-Wave JS to MQTT.
> Your request does not match the program running in this add-on.

@frenck Could you further explain how we bump the ZwaveJS version to v7.0.1? If viewed in the ZwaveJS2MQTT add-on in HA, it clearly shows that the ZwaveJS version is v7.0.0. Do I need to request this at https://github.com/zwave-js/zwavejs2mqtt? Sorry to ask a noob question.

**Comment by frenck** [comment]
yes

**Comment by DayRunner131** [comment]
> yes
> 
> Version requests on this end will always be closed. Even if valid.

Thanks!
