### ISSUE TITLE
Tilt sensor changes not registering since v0.9.1

### ISSUE THREAD

**Issue by krelltunez** [hassio-addons/addon-zwavejs2mqtt#108]
# Problem/Motivation

Ever since upgrading to v0.9.1, my garage tilt sensors are failing to log events.

## Expected behavior

Expect tilt sensors to register open/close (on/off) as normal.

## Actual behavior

No recognition of events.  I've tested/changed batteries, manually triggered tilt changes, etc.

## Steps to reproduce

Are other tilt sensors working?  Mine are "Vision Security" ZG8101 (bought from Monoprice).  They've always worked fine, including since moving to Z-Wave JS (and I've always used zwavejs2mqtt since making the switch).

## Proposed changes

This is where my knowledge ends... I have no idea why they're not working anymore or how to get them back.  Unfortunately, I chose not to backup the prior version of the addon when I upgraded to v0.9.1... I know, I know... this will teach me!

**Comment by frenck** [comment]
From an add-on perspective, this is not something I can fix. Add-ons wrap existing software. Please report your issue with the Home Assistant project.

Thanks 👍
