### ISSUE TITLE
Devices unavailable after HA restart - till before manual re-interview of all of them

### ISSUE THREAD

**Issue by Masterz69** [hassio-addons/addon-zwavejs2mqtt#109]
# Problem/Motivation

Today happened short power outage. HA node successfully started.
After some time I discovered: all ZWave nodes still unavailable.
In short - only manual re-interview for all nodes + integration restart helped.

Aeotec Stick was Ok, but other nodes not - only friendly name in list.
After every node re-interview: device info in Control Panel appears, like model etc.
But HA still not getting any data. Integration restart solved this las issue.

## Expected behavior

Expected: all devices become available w/out user intervention - after HA server was restarted,

## Actual behavior

All Z-Wave devices unavailable. In Control Panel they looks like:
![image](https://user-images.githubusercontent.com/15225823/113596578-315bb100-9643-11eb-94ce-17414d045e36.png)

Logs attached. Hope it will find the issue. 
[zwavejs2mqtt-store_20210405_11.zip](https://github.com/hassio-addons/addon-zwavejs2mqtt/files/6259205/zwavejs2mqtt-store_20210405_11.zip)
[zwavejs2mqtt-store_20210405_12.zip](https://github.com/hassio-addons/addon-zwavejs2mqtt/files/6259206/zwavejs2mqtt-store_20210405_12.zip)

## Steps to reproduce

Not sure.

**Comment by frenck** [comment]
This is not something the add-on can change. Addons wrap existing software, in this case: Z-Wave JS to MQTT. Please report your issue upstream. Thanks 👍
