### ISSUE TITLE
Missing from Add-on Store

### ISSUE THREAD

**Issue by AdamsLab01** [hassio-addons/addon-zwavejs2mqtt#112]
# Problem/Motivation

Searching the Home Assistant Add-on Store, I don't see Z-Wave JS to MQTT listed

## Expected behavior

I expected to see Z-Wave JS to MQTT listed and installable.

## Actual behavior

Z-Wave JS to MQTT is not listed.

## Proposed changes

I had it installed before but was having issues controlling a lock. Decided to start from the beginning, uninstalled everything z-wave related and went to re-install but don't see the Z-Wave JS to MQTT in the add on store.

**Comment by akennerly** [comment]
That add-on has been temporarily removed from the store.

https://twitter.com/hassioaddons/status/1379418322903691265

**Comment by TheDK** [comment]
More details here (PR with fix seems imminent):
https://github.com/zwave-js/zwavejs2mqtt/issues/1001

**Comment by robertsLando** [comment]
Can be closed

**Comment by frenck** [comment]
Yep, the add-on has been re-instated.
