### ISSUE TITLE
Problem afer update to 0.11.0

### ISSUE THREAD

**Issue by kimstor1435** [hassio-addons/addon-zwavejs2mqtt#118]
After update to 0.11.0 I don`t get any status on my nodes(unknown), also manufactor and model is gone.
I see in the log the the nodes are providing info and they are displayed in last active.

Any idea to solve this?

**Comment by frenck** [comment]
Have you tried a re-interview on those nodes?

**Comment by kimstor1435** [comment]
Hi Frenck
Yes I have, I also have a "spinning wheel" under the interview where it says: ProtocolInfo 
![image](https://user-images.githubusercontent.com/61433087/114146548-03fb5580-9918-11eb-9cec-a9c944e8617c.png)

**Comment by kimstor1435** [comment]
Zwave log:
![image](https://user-images.githubusercontent.com/61433087/114151063-06ac7980-991d-11eb-8e3f-915e82c8067d.png)

**Comment by frenck** [comment]
There is not much I can do about this. The add-on does not manage or change application logic. I think this issue belongs upstream.
