### ISSUE TITLE
Scene Notifications Stop Pushing to HA

### ISSUE THREAD

**Issue by Malklor** [hassio-addons/addon-zwavejs2mqtt#135]
# Problem/Motivation
Post upgrade to 2021.4.x all scene notifications from zwavejs2mgttt stop showing up in HA.   I was checking zwave_js_event in HA for these changes. I have read some breaking changes notes that imply this service should have changed.  I have reinstalled both zwavejs2mqtt and the HA zwaveJS integration but after clean installs and reboots of both of these the only service I see associated to zwave in the developer tools -> events tab is zwave_js_event.  

When watching log for zwavejs2mqtt debug logs I can see the scene being triggered 

`2021-04-18 09:22:29.875 INFO ZWAVE: Node 31: value notification: 91-0-scene-003 0
2021-04-18T14:22:29.878Z CNTRLR « [Node 031] received CentralScene notification {
"nodeId": 31,
"ccId": "Central Scene",
"ccCommand": "0x03",
"payload": "0xa48003"
}`

but when watching the zwave_js_event in the developer tools -> events tab no events are received.

**Comment by frenck** [comment]
This is not something related to the add-on, but Home Assistant itself.

Please read the release notes of Home Assistant 2021.4, as it was announced in those that the events changed.
