### ISSUE TITLE
SM103 device failing to report state to HA correctly

### ISSUE THREAD

**Issue by bazmk2** [hassio-addons/addon-zwavejs2mqtt#136]
# Problem/Motivation

Everspring SM103 devices no longer show correct state in HA.  These are window door sensors who should report open closed status.  This used to work prior to recent update about 10-20 days ago.

## Expected behavior

Sensor change when door window open and closed on to off etc

## Actual behavior

Sensor reports on either on or off on different devices.  No change on opening or closing of door.

Can see in debug status that the zwavejs is receiving the data as the level changes from 0 to 99 appropriately on open close but this does not transmit to HA

Rest of devices in zwave report and work as expected.  No issues with inclusion or exclusion.  I have rebuilt the zwave network from scratch on a different device and with different zwave stick with the same issue. Updated to most recent zwave2mqtt and HA

## Steps to reproduce

Use a SM103 in zwave network

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Hi m8!

Thanks for opening an issue. Unfortunately, from an add-on perspective, there is not much I can do about this issue. Please report this with the Home Assistant Core issue tracker.

Thanks! 👍 

../Frenck 🚂
