### ISSUE TITLE
ZW074 MultiSensor Gen5 motion sensor doesn't reset

### ISSUE THREAD

**Issue by matteskonto** [hassio-addons/addon-zwavejs2mqtt#139]
# Problem/Motivation

The motion sensor of AEON Labs ZW074 MultiSensor Gen5 doesn´t return from "7 - Motion Detected" after first trigger.
When I re-interview the node I get no motion on the sensor but when motion is first detected then it never resets again until I re-Interview again. Refresh values etc. does not fix this.

The sensor was working fine until some weeks ago after an update and I haven't update or changed any configuration on the sensor.

## Expected behavior

The motion sensor should reset after 240 secs of no motion.

## Actual behavior

The motion sensor never resets.

After a re-interview the motion is not triggered until a "real" motion so the sensor is working correctly. The sensor is powered by mains and has a good link to the controller, all other values (temp, lux, humidity) are updating just fine.

[node_43.json.txt](https://github.com/hassio-addons/addon-zwavejs2mqtt/files/6343406/node_43.json.txt)

**Comment by frenck** [comment]
This is not an issue the add-on can solve.

Add-on wrap existing software and you are reporting an issue with the software we wrap in this add-on. Please report this issue with the upstream project. Thanks 👍 

../Frenck 🚂
