### ISSUE TITLE
Ingress error: 400, message='Invalid response status'

### ISSUE THREAD

**Issue by Veldkornet** [hassio-addons/addon-zwavejs2mqtt#14]
# Problem/Motivation
I've been noticing this error in my Supervisor logs now and then:
`21-02-03 07:58:19 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 400, message='Invalid response status', url=URL('http://172.30.33.2:8099/socket.io/?EIO=4&transport=websocket&sid=_xxxxxxxxxxxxxxxx')`

The IP address is that of addon_a0d7b954_zwavejs2mqtt and this happens every time I open the "ZWave JS" panel /web interface.
I'm not sure if this is an issue or not to be honest. I just wanted to report it to confirm.

## Expected behavior
Unclear

## Actual behavior
Shows error. Unclear if it retries and is successful or...

## Steps to reproduce
Unclear

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by RogerSelwyn** [comment]
I also get this error whenever I open the web ui. The ui seems to work fine otherwise.

21-03-04 21:44:29 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 400, message='Invalid response status', url=URL('http://172.30.33.10:8099/socket.io/?EIO=4&transport=websocket&sid=MhkRL--HOZ5b5L_9AAAf')

**Comment by matteskonto** [comment]
I have the same behavior, throws an error every time I open the UI but everything works fine otherwise

**Comment by WouterKr** [comment]
I am having the same issue but the log show this error every 1to2 minutes even when the zwave2mqtt console is not active:

21-04-16 08:27:40 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 400, message='Invalid response status', url=URL('http://172.30.33.0:8099/socket.io/?EIO=4&transport=websocket&sid=r3RCLvIX2WDBD8fuAAAe')
21-04-16 08:29:07 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 400, message='Invalid response status', url=URL('http://172.30.33.0:8099/socket.io/?EIO=4&transport=websocket&sid=nP9AOAddsDIdJDfzAAAg')
21-04-16 08:30:36 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 400, message='Invalid response status', url=URL('http://172.30.33.0:8099/socket.io/?EIO=4&transport=websocket&sid=LR31Rl4QaipEObtdAAAi')
21-04-16 08:32:19 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 400, message='Invalid response status', url=URL('http://172.30.33.0:8099/socket.io/?EIO=4&transport=websocket&sid=9CW19mEp2tKXWJ0_AAAk')
21-04-16 08:33:05 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 400, message='Invalid response status', url=URL('http://172.30.33.0:8099/socket.io/?EIO=4&transport=websocket&sid=3rReAI9IhdI5ZxtSAAAo')

**Comment by frenck** [comment]
Fixed in v0.12.0

**Comment by cargnellogiacomo** [comment]
I still have the same issue also on version 0.14.1 .
