### ISSUE TITLE
Qubino ZMNHJD (flush pilot) - Temperature sensor isn't reported on some devices

### ISSUE THREAD

**Issue by dx44** [hassio-addons/addon-zwavejs2mqtt#143]
# Problem/Motivation

Some of my ZMNHJD devices have a multilevel sensor reported (air temperature) and some not.
When I was with OpenZWave, all my devices worked fine, the temperature entities were reported as well (although I don't use it because I don't have a probe).

I removed and reinstalled many times ZWaveJS2MQTT and it's not always the same devices that have this sensor missing, but always 2 of them (I have 5 devices, so 3 are working fine). I did a re-interview many time.

Also this devices, that had the temperature sensor missing, don't work because I'm unable to control the multilevel switch to change the heater mode (eco, comfort, etc).

## Expected behavior

Have the multilevel sensor reported on ALL devices and able to control the multilevel switch to change the heater mode.

Is this the right place about this type of issue ?

**Comment by dx44** [comment]
Some news : all my sensors are operationnels (I can on/off and define a mode), but 2 of them have the multilevel sensor missing.

What I did to fix them : I restarted HA, did a re-interview, waiting some hours that some missing sensors appears (other than the multilevel) and used the light.turn_on service.

Regards

**Comment by frenck** [comment]
Glad you got it resolved! 👍 

This would not have been the right place to report this issue. The add-on wraps existing software, in this case Z-WaveJS2MQTT. 

In general, however, for any z-wave issue, please report it with the HA org, as we try to manage all Z-Wave stuff from there.
