### ISSUE TITLE
MCO home MH-C421 multilevel switch is not good

### ISSUE THREAD

**Issue by S1M8N** [hassio-addons/addon-zwavejs2mqtt#144]
Hello,

I use home assistant OS without any add-on except zwavejs2mqtt which is in the latest version and the z-wave js integration that goes with it. However my C421 home MCO switches are not considered a multilevel switch (I think). I can still move them up and down I don't really know how but it works. On the other hand, it is impossible for me to do the STOP / PAUSE action ...

If you need a log please let me know where they are so I can send them to you. If I need an additional add on to retrieve these logs let me know

This is an issue that had already been addressed and corrected by adding a force multilevel switch for my device. When I did not yet have the add-on version it was good the force multievel switch worked but there it does not seem to work or badly ...
I noticed that if the module was in an unknown state everything was working in the management of the multilevel switch however when it is added correctly this is no longer the case and the stop button no longer works ...

I won't go into details because I don't really know how it works.

Hope we can solve this problem.

Thank you in advance 

Edit, I have open the same problem in this URL : https://github.com/zwave-js/node-zwave-js/issues/2454

**Comment by frenck** [comment]
Add-ons wrap existing applications and do not develop the application itself. This working is defined by Z-Wave JS, Home Assistant or the Z-Wave JS to MQTT project, from an add-on perspective, there is nothing I can do about this behavior.

Please report your issue upstream. Thanks 👍 

../Frenck 🚂
