### ISSUE TITLE
After power outage zwavejs2mqtt shows all devices Unknown manufacturer/product

### ISSUE THREAD

**Issue by cheikemate** [hassio-addons/addon-zwavejs2mqtt#145]
# Problem/Motivation

After a couple of months of a happy working with no issues Z-Wave JS to MQTT install I have my devices listed as Unknown manufacturer/product. All except my Z‐Stick Gen5 USB Controller.
All happen after a rather long and unusual power outage (5 hours).
When power was restored I could not get my devices back.
After two days only a few devices (the ones without battery - directly connected to power) had reapered.
I was forced to wake up all my other devices forcing a connect. Unfortunately I had to rename all the reconnected devices in the end. 
The devices are Alive and the Interview column shows as Completed. Some entities are on and others are offline. For example the battery values are available for most of the devices but the other device entities are not available.

## Expected behavior

I was expecting that my raspberry pi 4 Home Assistant install and my Zwave devices database could survive a power outage.
I never had this behavior before moving to Zwave JS. I had the same setup running without this issue on older Zwave and Openzwave integrations and never loosed the devices.

## Actual behavior

After coming up all devices were marked as "Unknown manufacturer/product".

## Steps to reproduce

I decided to simulate a new power outage to see if I could reproduce the problem.
I removed the power from my pi 4 and was able to reproduce the problem after removing the power cable and reconnecting it after a couple of minutes. 

## Proposed changes

I don't have any suggestion. I can provide additional information and maybe this troubleshooting helps others or helps improving the integration.

**Comment by cheikemate** [comment]
Screenshot of current status. 

![screen1](https://user-images.githubusercontent.com/38378514/116001320-d424a100-a5eb-11eb-8680-6bbc783be68c.png)

**Comment by cheikemate** [comment]
Screenshot of devices as seen by Z-Wave JS integration.

![screen2](https://user-images.githubusercontent.com/38378514/116001394-26fe5880-a5ec-11eb-9ed8-a66ba3f4143d.png)

**Comment by johntdyer** [comment]
I've had this happen two times now, its frustrating.   The first time I was able to get past it by manually re-interviewing all nodes...  The latest time I'm still dealing w/ the fallout....  After reinterviewing nodes I have hard wired switches that constantly go "dead" and I have to re-interview them...  Its very frustrating...  I am about to reset my network to try and get things working again.

**Comment by TheDK** [comment]
I once had a defective device in my kitchen throwing the fuse switch 2-3 times a day for a couple of days until I found it. Somewhere along the way a wall switch (Fibaro Single Switch) also went dead - I tried healing, restarting the network, anything - no luck. I then tried to exclude it - no luck. I had to open the wall switch, reset the device and include it again.

Best guess: During one of the power outages it lost the config. It appears highly unlikely that this happend to all devices. But if you complete restart the network, the controller starts contacting the devices and they just don't respond (maybe post the log after a full restart / powercycle of the device hosting the controller) there's nothing this Z-Wave JS (or this addon fwiw) can do...

**Comment by cheikemate** [comment]
I really don't know but what I can say that I have my Z-Wave setup since the openzwave integration. I migrated between the different Home Assistant Z-Wave implementations and this was the first time this happened (and twice).

Nevertheless I find the addon amazing. I just wish this will not happen again. 

Again... I can help to trace any issues providing logs and whatever is needed.

**Comment by TheDK** [comment]
To make sure that the Z Stick is power cycled as well I usually do this:
Shut down HA host via Supervisor - System
Wait until your Device is OFF AND the Disco lights on the Sticks are OFF
Disconnect power, wait a couple of seconds, reconnect power
Wait for boot and full Interview of Z-Wave JS
Post Log of this cycle of Z-Wave JS here

**Comment by blair287** [comment]
Had same issue today power cut only a brief one zwave stick shows but everything else is unknown and unable to control half my devices.

Why's it lost all the configs?
