### ISSUE TITLE
Updated to 14 and all devices disappeared from Control Panel

### ISSUE THREAD

**Issue by JAAlperin** [hassio-addons/addon-zwavejs2mqtt#155]
# Problem/Motivation

14 seems not to work (at least for me)

## Expected behavior

zwave devices in control panel should be there after update.

## Actual behavior

After update all devices were gone (driver load error)

## Steps to reproduce

For me, anyway, just click on update from 13 in supervisor.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by JAAlperin** [comment]
I reproduced it twice this morning, but not just now.  However, here is how the screen looked after update (see attachment).

My log is attached also, but probably won’t help.

Thank you, Franck.

Regards,

Jeff Alperin

H: 561-666-7789
C: 561-797-9876

**Comment by koburg** [comment]
I get some of the same problems some device will not get in it keeps scrolling arrow but it is a device with live power.
and the device is showing in the zwave js "normal" integration.

**Comment by koburg** [comment]
look like after reinstall the plugin serval times it looks better got the device in the config window
