### ISSUE TITLE
Failed to initialize the driver

### ISSUE THREAD

**Issue by Krojack** [hassio-addons/addon-zwavejs2mqtt#16]
Can't seem to get it to work. I did also try the official add-on "Z-Wave JS" and although no UI, it was able to see my devices. I removed that and installed this one but keep getting this error.

Complete log output: https://pastebin.com/Ci2QuEB6

My hardware:
```
serial:
  - /dev/ttyUSB0
  - >-
    /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_81300EB9-if00-port0
  - /dev/ttyUSB1
  - >-
    /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_81300EB9-if01-port0
```

The official add-on used **/dev/ttyUSB0**. I tried that and the full **/dev/serial/by-id/....**.
I don't have any secure devices but I was still able to get the network key from my HA **.storage/core.config_entries** file.

**Comment by jjmuriel** [comment]
Same here and the same USB dongle.

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Z-Wave JS to MQTT
 Fully configurable Z-Wave JS to MQTT gateway and control panel
-----------------------------------------------------------
 Add-on version: 0.3.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.10  (amd64 / qemux86-64)
 Home Assistant Core: 2021.2.1
 Home Assistant Supervisor: 2021.01.7
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] configuration.sh: executing... 
[cont-init.d] configuration.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[09:58:56] INFO: Starting the Z-Wave JS to MQTT...
 ______                       _     ___                  _   _   
|___  /                      (_)   |__ \                | | | |  
   / /_      ____ ___   _____ _ ___   ) |_ __ ___   __ _| |_| |_ 
  / /\ \ /\ / / _` \ \ / / _ \ / __| / /| '_ ` _ \ / _` | __| __|
 / /__\ V  V / (_| |\ V /  __/ \__ \/ /_| | | | | | (_| | |_| |_ 
/_____|\_/\_/ \__,_| \_/ \___| |___/____|_| |_| |_|\__, |\__|\__|
                            _/ |                      | |        
                           |__/                       |_|        
2021-02-05 09:58:56.496 WARN STORE: scenes.json not found
/bin/sh: git: not found
2021-02-05 09:58:57.337 INFO APP: Version: 1.0.5
2021-02-05 09:58:57.338 INFO APP: Application path:/opt
2021-02-05 09:58:57.364 INFO MQTT: MQTT is disabled
2021-02-05 09:58:57.372 INFO ZWAVE: Connecting to /dev/ttyUSB0
09:58:57.373 DRIVER   ███████╗ ██╗    ██╗  █████╗  ██╗   ██╗ ███████╗             ██╗ ███████╗
                      ╚══███╔╝ ██║    ██║ ██╔══██╗ ██║   ██║ ██╔════╝             ██║ ██╔════╝
                        ███╔╝  ██║ █╗ ██║ ███████║ ██║   ██║ █████╗   █████╗      ██║ ███████╗
                       ███╔╝   ██║███╗██║ ██╔══██║ ╚██╗ ██╔╝ ██╔══╝   ╚════╝ ██   ██║ ╚════██║
                      ███████╗ ╚███╔███╔╝ ██║  ██║  ╚████╔╝  ███████╗        ╚█████╔╝ ███████║
                      ╚══════╝  ╚══╝╚══╝  ╚═╝  ╚═╝   ╚═══╝   ╚══════╝         ╚════╝  ╚══════╝
09:58:57.374 DRIVER   version 6.1.2
09:58:57.374 DRIVER   
2021-02-05 09:58:57.392 INFO APP: Listening on port 44920
2021-02-05 09:58:57.407 INFO ZWAVE-SERVER: ZwaveJS server listening on port 3000
[09:58:57] INFO: Starting NGinx...
09:59:00.201 CNTRLR   beginning interview...
09:59:00.202 CNTRLR   querying version info...
09:59:01.283 CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                      n 100 ms.
09:59:02.386 CNTRLR   Failed to execute controller command after 2/3 attempts. Scheduling next try i
                      n 1100 ms.
09:59:04.493 DRIVER   Failed to initialize the driver: Timeout while waiting for an ACK from the con
                      troller
2021-02-05 09:59:04.494 INFO ZWAVE: Controller status: Driver: Failed to initialize the driver: Timeout while waiting for an ACK from the controller
[09:59:07] INFO: Successfully send discovery information to Home Assistant.

**Comment by jjmuriel** [comment]
`at Scheduler.process (/opt/node_modules/xstate/lib/scheduler.js:60:13)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
ZWaveError: Timeout while waiting for an ACK from the controller
    at Object.sendDataErrorToZWaveError (/opt/node_modules/zwave-js/src/lib/driver/StateMachineShared.ts:69:11)
    at /opt/node_modules/zwave-js/src/lib/driver/SendThreadMachine.ts:437:4
    at /opt/node_modules/xstate/lib/utils.js:410:33
    at Array.reduce (<anonymous>)
    at Object.updateContext (/opt/node_modules/xstate/lib/utils.js:400:25)
    at Object.resolveActions (/opt/node_modules/xstate/lib/actions.js:409:19)
    at StateNode.resolveTransition (/opt/node_modules/xstate/lib/StateNode.js:787:35)
    at StateNode.transition (/opt/node_modules/xstate/lib/StateNode.js:733:21)
    at StateNode.resolveRaisedTransition (/opt/node_modules/xstate/lib/StateNode.js:738:22)
    at StateNode.resolveTransition (/opt/node_modules/xstate/lib/StateNode.js:873:39)
    at StateNode.transition (/opt/node_modules/xstate/lib/StateNode.js:733:21)
    at /opt/node_modules/xstate/lib/interpreter.js:602:34
    at Object.provide (/opt/node_modules/xstate/lib/serviceScope.js:11:18)
    at Interpreter.nextState (/opt/node_modules/xstate/lib/interpreter.js:601:38)
    at /opt/node_modules/xstate/lib/interpreter.js:124:39
    at Scheduler.process (/opt/node_modules/xstate/lib/scheduler.js:60:13)
[12:58:19] INFO: Starting the Z-Wave JS to MQTT...
2021/02/05 12:58:20 [error] 416#416: *1574 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.32.2, server: a0d7b954-zwavejs2mqtt, request: "GET /socket.io/?EIO=4&transport=polling&t=NTpM48T&sid=ua0bdKg440XdjKC_AAAE HTTP/1.1", upstream: "http://127.0.0.1:44920/socket.io/?EIO=4&transport=polling&t=NTpM48T&sid=ua0bdKg440XdjKC_AAAE", host: "192.168.111.10:8123", referrer: "https://192.168.111.10:8123/api/hassio_ingress/2lkk8f-QRCzDZErOvVrRFrWghGiyOkrOEalhs-sUysw/"
2021/02/05 12:58:20 [error] 416#416: *1574 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.32.2, server: a0d7b954-zwavejs2mqtt, request: "POST /socket.io/?EIO=4&transport=polling&t=NTpM48p&sid=ua0bdKg440XdjKC_AAAE HTTP/1.1", upstream: "http://127.0.0.1:44920/socket.io/?EIO=4&transport=polling&t=NTpM48p&sid=ua0bdKg440XdjKC_AAAE", host: "192.168.111.10:8123", referrer: "https://192.168.111.10:8123/api/hassio_ingress/2lkk8f-QRCzDZErOvVrRFrWghGiyOkrOEalhs-sUysw/"`

**Comment by frenck** [comment]
@jjmuriel Use triple backticks to wrap code/text/logs 😉

**Comment by jjmuriel** [comment]
> @jjmuriel Use triple backticks to wrap code/text/logs 😉

Thanks!

**Comment by Krojack** [comment]
I fixed this. Mine is now working.
Follow this guide here: https://community.home-assistant.io/t/switching-from-zwave-1-4-to-zwave-js/276718

In short, if you still have the old Zwave integration installed then it will have total control over your Zwave USB stick. You need to remove the integration and reboot your host.  Just follow the guide I linked and you should be good. The ONLY part of the guide I changed is I installed zwavejs2mqtt rather than the official zwavejs add-on.
