### ISSUE TITLE
Config updates not working

### ISSUE THREAD

**Issue by mirkin1993** [hassio-addons/addon-zwavejs2mqtt#160]
# Problem/Motivation
Hassio gives the notification to update the config: 
"New zwave-js config version available: 7.3.1-20210503.

Mind that some changes may require a re-interview of affected devices"

But it isn't working.

## Expected behavior
Update the config

## Actual behavior
Error: 2021-05-05T12:46:28.131Z DRIVER   Config update failed: Package manager exited with code undefined

## Steps to reproduce
1. Open Zwave-JS to MQTT Addon
2. Go to config updates
3. Press install
4. Check log

**Comment by rowie1** [comment]
I Also have this issue

**Comment by DayRunner131** [comment]
Same issue here

**Comment by frenck** [comment]
Resolved in v0.15.0
