### ISSUE TITLE
Migration from Z-Wave to MQTT (DEPRECATED)

### ISSUE THREAD

**Issue by Gilles-Clemenceau** [hassio-addons/addon-zwavejs2mqtt#161]
Hello,
Is there a guide or something like that to move from Z-Wave to MQTT (https://github.com/hassio-addons/addon-zwave2mqtt) to this addon ?
Thanks.

**Comment by TheDK** [comment]
Thanks to Petro there is one:
https://community.home-assistant.io/t/switching-from-zwave-1-4-deprecated-to-zwavejs2mqtt/276721

Actually, several ones:
https://community.home-assistant.io/t/how-do-i-switch-to-zwave-js/276435

**Comment by Gilles-Clemenceau** [comment]
Thanks.
I saw it but I was wondering in case there was an official way.
I'll try with them.
