### ISSUE TITLE
REQUEST FEATURE "DELETE"

### ISSUE THREAD

**Issue by koburg** [hassio-addons/addon-zwavejs2mqtt#165]
All other wave controllers/gateways I have owned and used in the years. I have always been able to delete a device.

it is because some times it is needed either the system think it is there but actually not is. 
Then it keep the system busy trying to Heal og re-interview the device but can not because it is not there.

so you have to be able to delete and forget devices.

and the failed node is not enough because it can take hours before the system find it is not present.

**Comment by frenck** [comment]
Hi there @koburg 👋 

This is the issue tracker for the add-on. However, add-ons wrap existing software (in this case, Z-Wave JS to MQTT). We don't develop features in the add-on, so I cannot help you.

Please request features specific to the software program running inside the add-on, with the upstream project.

Thanks! 👍 

../Frenck 🚂
