### ISSUE TITLE
Ingress error: 400, message='Invalid response status'

### ISSUE THREAD

**Issue by cargnellogiacomo** [hassio-addons/addon-zwavejs2mqtt#168]
# Problem/Motivation

I've been noticing the same old error marked as fixed [here](https://github.com/hassio-addons/addon-zwavejs2mqtt/issues/14) also in the last version of the addon 0.14.1
In the Supervisor log I see this warning everytime I open the webpage of the zwavejs2mqtt addon:
21-05-13 09:29:45 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 400, message='Invalid response status', url=URL('http://172.30.33.2:8099/socket.io/?EIO=4&transport=websocket&sid=Ilj5V7tcb_qj3Jo6AAAQ')

## Expected behavior

Unclear

## Actual behavior

Shows error. 

## Steps to reproduce

Unclear

## Proposed changes

Unclear

**Comment by deku-m** [comment]
Got the same when checking or changing values in zwavejs controlpanel.
21-05-25 13:37:37 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 400, message='Invalid response status', url=URL('http://172.30.33.3:8099/socket.io/?EIO=4&transport=websocket&sid=HvywT6UzzthdVp6lAAAA')

**Comment by gairom** [comment]
I'm getting similar errors but when calling the Grafana container
`21-06-26 01:25:58 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 400, message='Invalid response status', url=URL('http://172.30.33.3:1337/api/live/ws')`

**Comment by crcerdas** [comment]
Similar problem here, any solution?

**Comment by deiger** [comment]
Still happens, in version 0.21.0.

**Comment by Wariole** [comment]
I'm also getting this error with version 0.21.0.

**Comment by flaterichd** [comment]
Also the same issue  0.22.0

**Comment by Wariole** [comment]
Still getting it with 0.22.0.
Is there any information we should provide to help tackle this issue?

**Comment by TheDK** [comment]
Same here. It is working fine though…

**Comment by gazoo-i** [comment]
i am having this issue also. not sure how to overcome?

the web UI doesn't load in the addon. have tried various usb ports but does not work.

**Comment by Menzo555** [comment]
Same issue here, WebUI isn't loading, if I clear my browser cache, it works, but stops after that.  I've tried Firefox, Chrome, Edge, all seem to have the same issue.  Seems to be affecting more Add-Ons than just the ZWavejs2mgtt though for me.  Running on HA Blue (odroid).  The app seems to work fine though...

**Comment by gazoo-i** [comment]
ended up changing z-wave hub and the issue is fixed. i believe this 400 ingress error is non z-wave related...

**Comment by guineau** [comment]
I am also seeing this on HA OS, RPi4, Nortek zwave/zigbee USB stick. It's been occurring for pas several updates to HA CORE and zwavejs2mqtt add-on.

**Comment by Menzo555** [comment]
Also seeing it on my HA Blue Odroid - affects all the addons with a webui component, but the iOS app seems to be mostly ok.  Firefox seems to be the worst, but have issues on Edge and Chrome too.  Resetting Firefox seems to temporarily fix it as well, but it stops working eventually.  Been having this issue for over a week now.  Anybody have any luck finding what might be causing it?

**Comment by gazoo-i** [comment]
what z-wave stick are you using and how do you have it mapped?

**Comment by Menzo555** [comment]
I'm using a zooz S2 USB stick.  Mapped through serial ID on the USB.  The issue appears to be more than just with the zwave2mqtt add-on.  None of my add-ons with webui's work from my computer browser.

**Comment by jhein05** [comment]
Getting this error message too, but everything seems to work anyway.
HA Blue Hardware with Aeotec ZWave stick directly plugged in on 2m USB extension cord.

**Comment by cargnellogiacomo** [comment]
I solved adding zwavejs2mqtt as a container in Docker using the [official image](https://hub.docker.com/r/zwavejs/zwavejs2mqtt). It works perfectly now since weeks.
I used docker compose:
`  zwave:
    container_name: ZWave
    image: 'zwavejs/zwavejs2mqtt:latest'
    restart: always
    tty: true
    stop_signal: SIGINT
    environment:
      - TZ=Europe/Amsterdam # uncomment and edit to match you timezone if you want logs time and dates to match your timezone instead of UTC.
    devices:
      - '/dev/ttyAMA0:/dev/ttyAMA0'
    volumes:
      - /home/pi/Docker_Data/zwavejs2mqtt:/usr/src/app/store
    ports:
      - '8091:8091' # port for web interface
      - '3000:3000' # port for zwave-js websocket server`

/dev/ttyAMA0 is used in case you have a z-wave GPIO board. If you have a USB stick, then you need to change it.
For Pi4, you need also to do the following:
1. modify the file "/boot/config.txt" and add (or uncomment) the following lines:
 dtoverlay=disable-bt
 enable_uart=1
 dtoverlay=pi3-miniuart-bt
2. modify the file "/boot/cmdline.txt" and remove "console=serial0,115200"
3. do not install the zwave.me software to avoid conflicts

I hope this will help.

**Comment by heyepic** [comment]
Yep, same here for my setup. Running HUSBZB-1 mapped as /dev/ttyUSB0 (Synology VM)

**Comment by aziob** [comment]
I have the same issue. The z-wave stick in use is The Aeon Labs Z‐Stick Gen5 USB Controller. The serial device mapping is in the form `/dev/serial/by-id/usb-nnnn_nnnn-llnn`.

**Comment by remimikalsen** [comment]
Same problem here, and I have som additional info from my log.

21-08-23 09:06:51 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 400, message='Invalid response status', url=URL('http://172.30.33.1:8099/socket.io/?EIO=4&transport=websocket&sid=Ewv48__CWn8vGrpkAAAU')

The error appears whenever I open the Z-Wave JS Control Panel. Also, setting the controller in inclusion and exclusion mode result in "Error while calling api startInclusion: The inclusion could not be started."

Z-Wave JS to MQTT version: 0.23.5
Core version: core-2021.8.8

I set the Z-Wave JS to MQTT add-on ro debug-logging and got this:

2021-08-23 09:19:23.204 INFO APP: GET /health/zwave 200 47.751 ms - 1875
2021-08-23 09:19:23.849 INFO APP: GET / 200 3.353 ms - 1875
2021-08-23 09:19:24.319 INFO APP: GET /api/auth-enabled 200 19.977 ms - 29
2021-08-23 09:19:25.037 INFO APP: GET /api/settings 200 286.504 ms - 303804
2021-08-23 09:19:25.245 INFO APP: GET /api/auth-enabled 304 7.860 ms - -
2021-08-23 09:19:29.776 INFO ZWAVE: Calling api startInclusion with args: [ false, [length]: 1 ]
2021-08-23 09:19:29.899 INFO ZWAVE: The inclusion could not be started. startInclusion undefined
2021-08-23 09:19:29.975 INFO ZWAVE: Controller status: Inclusion stopped

**Comment by GaTechThomas** [comment]
> I have the same issue. The z-wave stick in use is The Aeon Labs Z‐Stick Gen5 USB Controller. The serial device mapping is in the form `/dev/serial/by-id/usb-nnnn_nnnn-llnn`.

I have this issue as well, exactly the same setup as @aziob.

**Comment by remimikalsen** [comment]
I got the controller working by unplugging and plugging it in again. So far, this only happened once over the course of a few months.

**Comment by Mpgod80** [comment]
> Got the same when checking or changing values in zwavejs controlpanel.
> 21-05-25 13:37:37 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 400, message='Invalid response status', url=URL('http://172.30.33.3:8099/socket.io/?EIO=4&transport=websocket&sid=HvywT6UzzthdVp6lAAAA')

I get the same error as soon as i enter  zwavejs controlpanel.

21-09-28 11:40:15 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 400, message='Invalid response status', url=URL('http://172.30.33.1:8099/socket.io/?EIO=4&transport=websocket&sid=QERfPmTMhaonBCHyAAAI')

Is there anyone looking into what the problem is?

**Comment by Menzo555** [comment]
My fix was reducing the security settings on my Firefox browser.  Had to disable the 'Enhanced Browser Protection' for my HA site.

**Comment by continuousmining** [comment]
+1 to this as well on latest version.

**Comment by Reydan46** [comment]
+1 to this as well on latest version.

**Comment by Alan-Guggenheim** [comment]
Same error
21-12-03 09:46:04 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 400, message='Invalid response status', url=URL('http://172.30.33.3:8099/socket.io/?EIO=4&transport=websocket&sid=pryoFdQZyW9UOKJJAAAG')

**Comment by jamespreedy** [comment]
Same here sadly.

22-01-02 14:58:06 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 400, message='Invalid response status', url=URL('http://172.30.33.2:8099/socket.io/?EIO=4&transport=websocket&sid=_ygSJYU05VLvzOklAAAw')

**Comment by fisch55** [comment]
Same issue here …..
