### ISSUE TITLE
iBlinds lost 1-100 slider support

### ISSUE THREAD

**Issue by mifbody** [hassio-addons/addon-zwavejs2mqtt#171]
After updating to the latest version 0.15.0 my iBlinds motorized blinds devices no longer have the 1-100 slider support. I can see in the ZWave JS that the device has a multilevel switch, but it's not translating into Home Assistant. In home assistant the devices has an up arrow, stop, and down arrow, but no slider like I used to have.

**Comment by TheDK** [comment]
I had this once or twice for blinds and dimmer switches with the old ZWave 1.4 integration: Have you tried a) a restart of HA and b) a refresh of the browser / app?

Nevertheless, this issue will be closed soon as it‘s either a problem with HA itself or the upstream project, not this add-on, which just  wraps the ZWJS2MQTT functionality.

**Comment by frenck** [comment]
Hi there @mifbody 👋 

Add-ons wrap existing software, in this case, ZWaveJS2MQTT. From an add-on perspective, there is nothing I can do. Please report your issue upstream in this case.

Thanks! 👍 

../Frenck
