### ISSUE TITLE
ZWaveJS integration conflicting / keeps trying to open USB stick port

### ISSUE THREAD

**Issue by yetdog** [hassio-addons/addon-zwavejs2mqtt#181]
# Problem/Motivation

I noticed high CPU on my HA instance. Looked like the ZWaveJS addon was causing it. Looking at the log, it kept attempting to open my ZWave USB stick, but couldn't get access to it, as ZWaveJS2MQTT had hold of it. Stopping ZWaveJS clears things up, and then I uninstall the addon. However, at every restart of HA, (and actually automatically even without a reboot), it seems the ZwaveJS addon gets reinstalled, and the CPU/conflict problem crops up again.

Am I fundamentally misunderstanding the relationship between ZwaveJS and ZWaveJS2MQTT? It seems to operate just fine with just the ZwaveJS2MQTT addon running.

## Expected behavior

I thought the ZWaveJS2MQTT was its own standalone integration, and ZWaveJS could be uninstalled. Or, if that assumption is wrong (as it sounds likely), and ZWaveJS is still required on the backend, it wouldn't be trying to open the USB device port, and leave it alone for ZWaveJS2MQTT to handle it. 

## Actual behavior

CPU on my HA host goes up, and the ZWaveJS integration log repeats this following block:
```
2021-05-27T14:08:58.133Z DRIVER   ███████╗ ██╗    ██╗  █████╗  ██╗   ██╗ ███████╗             ██╗ ███████╗
                                  ╚══███╔╝ ██║    ██║ ██╔══██╗ ██║   ██║ ██╔════╝             ██║ ██╔════╝
                                    ███╔╝  ██║ █╗ ██║ ███████║ ██║   ██║ █████╗   █████╗      ██║ ███████╗
                                   ███╔╝   ██║███╗██║ ██╔══██║ ╚██╗ ██╔╝ ██╔══╝   ╚════╝ ██   ██║ ╚════██║
                                  ███████╗ ╚███╔███╔╝ ██║  ██║  ╚████╔╝  ███████╗        ╚█████╔╝ ███████║
                                  ╚══════╝  ╚══╝╚══╝  ╚═╝  ╚═╝   ╚═══╝   ╚══════╝         ╚════╝  ╚══════╝
2021-05-27T14:08:58.137Z DRIVER   version 7.5.2
2021-05-27T14:08:58.138Z CONFIG   version 7.5.2
2021-05-27T14:08:58.138Z DRIVER   
2021-05-27T14:08:58.163Z DRIVER   Serial port errored: Error Resource temporarily unavailable Cannot lock port
Unable to start driver [Error: Error Resource temporarily unavailable Cannot lock port]
[07:08:58] INFO: Successfully send discovery information to Home Assistant.
```

## Steps to reproduce

While ZWaveJS2MQTT integration is running (and working), either manually start (or just wait - it will get started automatically at some point) the ZWaveJS integration.

**Comment by frenck** [comment]
I think you are confusing the Z-Wave JS add-on (core) and the Z-Wave JS 2 MQTT add-on. Both can do the same thing. You can't use both. A serial port can only be used by 1 piece of software at the time.

**Comment by frenck** [comment]
That is not an issue with this add-on, so you are reporting it in the wrong place.

**Comment by yetdog** [comment]
Thanks for the confirmation that ZWaveJS2MQTT doesn't rely on or require the ZWaveJS addon. That's a help.
