### ISSUE TITLE
Eurotronics Spirit Valve mode

### ISSUE THREAD

**Issue by WouterKr** [hassio-addons/addon-zwavejs2mqtt#182]
# Problem/Motivation
It is not possible to select valve mode / Manufacturer Specific for the Eurotronics Spirit thermostat.

## Expected behavior
Option to set the valve percentage

## Actual behavior
Not able to choose valve mode / Manufacturer Specific

## Proposed changes
I would like to see the option to activate the valve mode   so I can set the valve percentage and not the temperature.

**Comment by frenck** [comment]
That is not something I can help with. Add-on wrap existing software, we don't develop Z-WaveJS2MQTT, please report your request upstream with the Z-Wave JS project.
