### ISSUE TITLE
[FR] Selecting ZWAVE device in control panel by /dev/serial/by-id/xxxx/

### ISSUE THREAD

**Issue by deku-m** [hassio-addons/addon-zwavejs2mqtt#187]
# Problem/Motivation

I wonder if it is possible to have the Zwave stick selected by serial-id like in the conbee add-on for example.
As sometimes with the ACM0/1 it not clear and could be a failure.

## Expected behavior

Selecting the Wave stick by /dev/serial/by-id/xxxxx/

## Actual behavior

Nothing it isn't possible.

## Steps to reproduce

In control panel under zwave 
Check Serial Port:
Only selectable by /dev/ttyACM0/1 or USB

## Proposed changes
Selectable by /dev/serial/by-id/xxxxx/
Its just handy and more reliable.

**Comment by frenck** [comment]
It does that already.

**Comment by deku-m** [comment]
> 
> 
> It does that already.
> 
> ![image](https://user-images.githubusercontent.com/195327/120069009-e6c74580-c083-11eb-8eaf-b5f0cb4451b2.png)

Sorry for that didnt know.
Can you tell me maybe why im not able to select it by serial ID. Might you know if this is a configuration issue?

**Comment by frenck** [comment]
That is more a question of how your system is configured. The add-on doesn't care, it just shows what is available/provided.
