### ISSUE TITLE
New zwave-js config version available: 7.7.2-20210602.  Mind that some changes may require a re-interview of affected devices

### ISSUE THREAD

**Issue by trentjw** [hassio-addons/addon-zwavejs2mqtt#191]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Empty issue.
