### ISSUE TITLE
Z-Wave JS Integration fails to connect to Z-Wave JS to MQTT add-on after core-2021.6.0

### ISSUE THREAD

**Issue by OtherStep** [hassio-addons/addon-zwavejs2mqtt#192]
### My first issue, so be gentle!

# Problem/Motivation

After upgrade to core-2021.6.0, working Z-Wave JS Integration to Z-Wave JS to MQTT addon v0.16.0 failed with the following error:

> Logger: homeassistant.config_entries
> Source: config_entries.py:324
> First occurred: 10:48:53 AM (1 occurrences)
> Last logged: 10:48:53 AM
> 
> Config entry 'Z-Wave JS' for zwave_js integration not ready yet: Z-Wave JS Server version is incompatible: 1.5.0 a version is required that supports at least api schema 5; Retrying in background

JS to MQTT addon working as expected without errors.

## Steps to reproduce

Install and configure Z-Wave JS to MQTT add-on 0.16.0.  Install Z-Wave JS Integration in core-2021.6.0 and connect to localhost:3000 (default config, previously working).  Full system health copied below.

## Proposed changes

Suspect the integration or addon needs to be updated to schema 5.  Couldn't find reference to schema 5 or Z-Wave JS Server version 1.5.0 in the documentation or release notes.

## System Health

version | core-2021.6.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.9
os_name | Linux
os_version | 5.4.83-v8
arch | aarch64
timezone | America/New_York

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4959
Installed Version | 1.12.4
Stage | running
Available Repositories | 823
Installed Repositories | 2

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 5.13
-- | --
update_channel | stable
supervisor_version | supervisor-2021.05.4
docker_version | 19.03.15
disk_total | 28.6 GB
disk_used | 3.2 GB
healthy | true
supported | true
board | rpi3-64
supervisor_api | ok
version_api | ok
installed_addons | SSH & Web Terminal (8.2.1), Z-Wave JS to MQTT (0.16.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>

**Comment by frenck** [comment]
> Z-Wave JS to MQTT add-on 0.16.0

The add-on is already at 0.18.1, please upgrade.

**Comment by OtherStep** [comment]
Thanks @frenck , after digging around I realized something is broken with my supervisor DNS resolution so it wasn't pulling updates from the add-on store.

**Comment by frenck** [comment]
No problem! Glad you figured it out 👍
