### ISSUE TITLE
Issue again with with Leviton Switches since 19.4

### ISSUE THREAD

**Issue by frogbite** [hassio-addons/addon-zwavejs2mqtt#201]
# Problem/Motivation

Several months ago I had an issue where my Leviton switches would get included but what show as dead.  I got everything working by doing a secure exclusion though my zstick.  Since upgrading Home Assistant and zwavejs2mqtt when 19.4 came out the devices are now showing as dead again.  

## Expected behavior

After upgrades of Home Assistant and the add-on I expected that the switches would remain alive.  They had been very consistent since the recent upgrades. 

## Actual behavior

First I noticed that one of the switches was not working via HA.   I looked in the zwave panel and the device showed as dead.  My other switch showed as alive though and went to activate that switch and it changed to dead.  

2021-06-22 18:39:28.205 INFO ZWAVE: Node 9: interview stage PROTOCOLINFO completed
2021-06-22 18:39:28.319 INFO ZWAVE: Node 10: interview stage PROTOCOLINFO completed
2021-06-22 18:39:32.680 INFO ZWAVE: Node 10 is dead
2021-06-22 18:39:36.969 INFO ZWAVE: Node 9 is dead
2021-06-22 18:39:36.974 INFO ZWAVE: Controller status: Scan completed
2021-06-22 18:39:36.977 INFO ZWAVE: Network scan complete. Found: 5 nodes
2021-06-22 18:39:41.193 ERROR ZWAVE: Interview of node 10 has failed: The node is dead
2021-06-22 18:39:45.356 ERROR ZWAVE: Interview of node 9 has failed: The node is dead

## Steps to reproduce

Now it is consistent.  I have tried excluding and including the switches and then went through several Heal Network and reboots but the switches still show as dead.  

![image](https://user-images.githubusercontent.com/38390153/123010029-d0af5b00-d38b-11eb-9ae5-c75f11b73064.png)

[nodes_dump.txt](https://github.com/hassio-addons/addon-zwavejs2mqtt/files/6697857/nodes_dump.txt)

**Comment by frogbite** [comment]
This is interesting, I deleted one of the dead nodes and the other came alive.   I did an interview and it went dead again, but then it came back when I tried to delete it via the add-on:

[zwave.pdf](https://github.com/hassio-addons/addon-zwavejs2mqtt/files/6698062/zwave.pdf)

**Comment by frogbite** [comment]
Did an exclude and include on the dead node and added it back in.  It came back again dead.  Went to delete the node and got the message it could not be deleted because it answered to a ping.  Then the working switch went to a dead status.  I tried to delete that one and it came back as the ping succeeded.   

Something is not right, it is almost like there is something conflicting. 

[zwave_both_working.pdf](https://github.com/hassio-addons/addon-zwavejs2mqtt/files/6698144/zwave_both_working.pdf)
[nodes_dump_working.txt](https://github.com/hassio-addons/addon-zwavejs2mqtt/files/6698157/nodes_dump_working.txt)

**Comment by frogbite** [comment]
![image](https://user-images.githubusercontent.com/38390153/123017908-8d5ce880-d39b-11eb-9ee3-18790a5074c9.png)

**Comment by sinclairpaul** [comment]
The addon wraps the software from https://github.com/zwave-js/zwavejs2mqtt

I would suggest that would be a better place to log your issue

**Comment by frogbite** [comment]
The last time I had a similar issue I started there and was pushed from project to project and ended here.   I will go ahead and open an issue there and refer this one.  The last time I had 5 issues open  with 5 different projects as the issue was perceived to be "not in this area".  But I can see your point.

**Comment by frenck** [comment]
Add-ons wrap existing software, there is not much we can do about it here. Sorry, m8.
