### ISSUE TITLE
Danalock square BTZW125 - wrong device config loaded

### ISSUE THREAD

**Issue by kfazon** [hassio-addons/addon-zwavejs2mqtt#206]
> After adding this danalock lock it loads the wrong device config. The link to zwavejs db on Device ID
270-2-3 (0x010e-0x0003-0x0002) is ok and there is a right config in zwavejs database. But the loaded cofig is from an unknown lock

**Comment by frenck** [comment]
Hi there @kfazon 👋 

This is an add-on, and add-ons wrap existing software. In this case Z-Wave JS to MQTT.
Please report this kind of issues upstream, as soon as they get fixed and updated, the add-on will update as well.

../Frenck
