### ISSUE TITLE
Network graph not working well

### ISSUE THREAD

**Issue by mirkin1993** [hassio-addons/addon-zwavejs2mqtt#214]
# Problem/Motivation
The network graph doesn't show the neighbor connections, all devices are positioned next to each other without any lines

## Expected behavior
See the connections between the z-wave deviced and the neighbors

## Actual behavior
See problem/motivations

## Steps to reproduce
-

## Proposed changes
-

**Comment by TheDK** [comment]
Have you a) re-interviewed the controller und the nodes, b) restarted the add-on and C) restarted HA? I saw the same and it simply took a couple of days / restarts / etc. until everything showed correctly...

**Comment by frenck** [comment]
Hi there @mirkin1993 👋 

Unfortunately, there is nothing the add-on can do with your feedback. Add-ons wrap existing applications, in this case, Z-Wave JS to MQTT. Please report your suggestion with the upstream project. If it gets addressed and release, the add-on will update at that point in time as well.

Thanks!

../Frenck
