### ISSUE TITLE
0.23.1 and Manufacturer and Product Names

### ISSUE THREAD

**Issue by Hajman** [hassio-addons/addon-zwavejs2mqtt#222]
# Problem/Motivation

web UI of 0.23.1 lists all Manufacturers and Product Names as Unknown

## Expected behavior

Web UI to properly show the manufacturer and product names based on ID

## Actual behavior

see problem description above

## Steps to reproduce

Updated from 0.22.1 to 0.23.1 and the error occurred.  I rolled back to 0.22.1 via snapshot and manufacturers and product names appear properly.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by oz9els** [comment]
Same issue here, just updated, rebooted.
![image](https://user-images.githubusercontent.com/61284428/126654782-43caa2b1-7d3d-4a7a-a53a-ac4f53bcc115.png)

All devices listed like this:
Unknown manufacturer 0xXXXX | 0xXXXX | Unknown product 0xXXXX

**Comment by frenck** [comment]
Confirmed, seeing the issue appearing on my end now as well.

**Comment by frenck** [comment]
Ok, that was fast found, upstream bug: <https://github.com/zwave-js/zwavejs2mqtt/issues/1469>
The fix is inbound!

**Comment by oz9els** [comment]
WOW ultra fast problem solving - Thanks Frenck.

**Comment by frenck** [comment]
I'm not the one to thanks, its been fixed by the guys upstream @ the Z-Wave JS project ❤️

**Comment by Hajman** [comment]
Thanks all.
