### ISSUE TITLE
FGS-224 missing meter parameters, on FGS-223 all are avaiable

### ISSUE THREAD

**Issue by mario5046** [hassio-addons/addon-zwavejs2mqtt#226]
Hello
I noticed that Fibaro FGS-224 is not correctly supported in the latest version of zwaves2mqtt.
On FGS-223 are avaiable meter tab with the power consumption etc., on FGS-224 these option are not avaiable.

**Comment by osochor** [comment]
It' not a bug it's a feature.
The FGS224 doesnt support **Electric active power** and **Electric  energy**

**Comment by frenck** [comment]
As per the answer above.
