### ISSUE TITLE
Add-on update failing

### ISSUE THREAD

**Issue by Masterz69** [hassio-addons/addon-zwavejs2mqtt#228]
# Problem/Motivation

Add-on 0.22.1 update to 0.23.2 failing:

![image](https://user-images.githubusercontent.com/15225823/127130107-d21853a8-7727-4eb8-b0a6-ddfdd895d4c6.png)

## Steps to reproduce

HA -> Supervisor -> Z-Wave JS to MQTT -> Update

**Comment by Masterz69** [comment]
## System Health

version | core-2021.7.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.9.5
os_name | Linux
os_version | 5.10.17-v8
arch | aarch64
timezone | Europe/Riga

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.13.2
Stage | running
Available Repositories | 912
Installed Repositories | 20

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | failed to load: timeout

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.1
-- | --
update_channel | stable
supervisor_version | supervisor-2021.06.8
docker_version | 20.10.6
disk_total | 54.3 GB
disk_used | 13.5 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Samba Backup (4.5.0), SSH & Web Terminal (9.0.0), File editor (5.3.3), Mosquitto broker (5.1.1), Z-Wave JS to MQTT (0.22.1), Zigbee2mqtt (1.18.2-1), MariaDB (2.4.0), phpMyAdmin (0.4.3), Samba share (9.5.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 8
-- | --
resources | 8
views | 29
mode | storage

</details>

**Comment by Masterz69** [comment]
````
21-07-27 11:30:34 INFO (MainThread) [supervisor.snapshots] Creating new partial-snapshot with slug 9c6ac7b4
21-07-27 11:30:34 INFO (MainThread) [supervisor.snapshots] Snapshotting 9c6ac7b4 store Add-ons
21-07-27 11:30:34 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_zwavejs2mqtt
21-07-27 11:32:56 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_zwavejs2mqtt
21-07-27 11:32:58 INFO (MainThread) [supervisor.snapshots] Creating partial-snapshot with slug 9c6ac7b4 completed
21-07-27 11:32:58 INFO (SyncWorker_3) [supervisor.docker.interface] Updating image ghcr.io/hassio-addons/zwavejs2mqtt/aarch64:0.22.1 to ghcr.io/hassio-addons/zwavejs2mqtt/aarch64:0.23.2
21-07-27 11:32:58 INFO (SyncWorker_3) [supervisor.docker.interface] Downloading docker image ghcr.io/hassio-addons/zwavejs2mqtt/aarch64 with tag 0.23.2.
21-07-27 11:33:13 ERROR (SyncWorker_3) [supervisor.docker.interface] Can't install ghcr.io/hassio-addons/zwavejs2mqtt/aarch64:0.23.2: 404 Client Error for http+docker://localhost/v1.41/images/ghcr.io/hassio-addons/zwavejs2mqtt/aarch64:0.23.2/json: Not Found ("no such image: ghcr.io/hassio-addons/zwavejs2mqtt/aarch64:0.23.2: No such image: ghcr.io/hassio-addons/zwavejs2mqtt/aarch64:0.23.2")
```

**Comment by frenck** [comment]
It exists, see: <https://github.com/hassio-addons/addon-zwavejs2mqtt/pkgs/container/zwavejs2mqtt%2Faarch64>

This is happening outside the scope of the add-on, from an add-on perspective, there is nothing I can do.

**Comment by Masterz69** [comment]
Thank You very much. It installed by 2nd try. Have a nice day.

**Comment by frenck** [comment]
Glad you got it resolved!

Good day to you too sir!

![](https://media3.giphy.com/media/igsrACBKNTD4fCMUCN/giphy-downsized-medium.gif)
