### ISSUE TITLE
ZW31 S2 In-wall Smart Dimmer switch Unknown when Added

### ISSUE THREAD

**Issue by nvOC-Stubo** [hassio-addons/addon-zwavejs2mqtt#240]
On 0.23.5 adding ZW31 (NIE Technology Co., Ltd. / S2 In-wall Smart Dimmer switch) dimmers via Control Panel Action|Add/Remove Device|Inclusion (or Secure Inclusion) results in successful device addition but unknown manufacturer, product, and product code. The device works otherwise. Also, the control panel has a message at the top saying "Driver: Node XXX supports Security S2, but no network key was configured. Continuing interview non-securely". 

I purchased several of these devices from an online retailer and am wondering if maybe I received defective units. I have successfully added over 30 other Z-wave devices (switches, dimmers, etc.) and this is the first issue I have had.

**Comment by nvOC-Stubo** [comment]
Providing additional information as I learn more. On my Z-Wave JS to MQTT Control Panel, I see the following for these devices:
Manufacturer: 0x0312
Product: 0xaa00
Product Code: 0xaa02

When I look at the device database, that information seems to match this device entry which is the correct one:
https://devices.zwave-js.io/?jumpTo=0x0312:0xa000:0xaa02:0.0

So the question is why is my installation not finding it and reporting these as "unknown" instead?

**Comment by nvOC-Stubo** [comment]
More information. If found the device (matching manufacturer, product, product code) in ~db/devices/index.json:

	_{
		"manufacturerId": "0x0312",
		"manufacturer": "NIE Technology Co., Ltd.",
		"label": "ZW31",
		"productType": "0xa000",
		"productId": "0xaa02",
		"firmwareVersion": {
			"min": "0.0",
			"max": "255.255"
		},
		"filename": "0x0312/zw31.json",
		"rootDir": "/data/db/devices"
	},_

Now I am trying to figure out why the integration is not finding this apparent match.

**Comment by frenck** [comment]
Hi there @nvOC-Stubo 👋 

Add-ons wrap existing software, in this case the Z-Wave JS 2 MQTT project. Please report issues with Z-Wave JS itself upstream.

Thanks! 👍 

../Frenck
