### ISSUE TITLE
v0.28.0 causes dongle to be disconnected from VM

### ISSUE THREAD

**Issue by embcla** [hassio-addons/addon-zwavejs2mqtt#288]
# Problem/Motivation

I have auto-update and since yesterday (release day of 0.28.0) whenever this addon is started, the zwave usb dongle is disconnected from the HA virtual machine.

## Expected behavior

That it continued working like before, leaving the dongle attached to the VM.

## Actual behavior

That whenever the addon is started, the dongle is detached from the VM.

## Steps to reproduce

QNAP x86 NAS with Virtualization Station
Debian 10 VM guest with Home Assistant installed
zwave _Aeotec Z-Stick Gen5 (ZW090) - UZB_ stick connected to the QNAP and attached to the VM
Version 0.28.0 when ran, will cause the dongle to be detached
Version 0.18.0 (latest backup I had, but probably any version up until 0.28.0 excluded) **does not cause it**

**Comment by sinclairpaul** [comment]
Maybe look at #287 #286

**Comment by frenck** [comment]
Sounds like your setup can't handle soft reset, please disable it in the Z-Wave JS 2 MQTT configuration.
