### ISSUE TITLE
Aeotec ZW141 Shutter inverted buttons in lovelace

### ISSUE THREAD

**Issue by asemev** [hassio-addons/addon-zwavejs2mqtt#296]
Hi, is there a way to invert the buttons in the lovelace? Current pressing up closes the shutters. Previously i had the same shutter connected with SmartThings and the buttons were working correctly. Any help would be appreciated. Thx.

**Comment by frenck** [comment]
The add-on cannot do anything about that :)

You might need to report an issue upstream with Home Assistant for that matter.
