### ISSUE TITLE
Bug in underlying zwaveJS server fixed, addon needs update to current version of zwavejs2mqtt

### ISSUE THREAD

**Issue by mwav3** [hassio-addons/addon-zwavejs2mqtt#308]
# Problem/Motivation

ZwaveJS 8.8.0 had a major rewrite for outgoing message handling.  This resulted in bugs that were crashing users Zwave networks as discussed in these threads/issues:

https://community.home-assistant.io/t/all-controls-switches-shutters-etc-stop-working-after-a-while/362139
https://github.com/zwave-js/node-zwave-js/issues/3811
https://github.com/zwave-js/node-zwave-js/issues/3829

ZwaveJS released 8.8.3 to revert the outgoing message handling code changes due to these bugs, and that update has been incorporated into ZwaveJS2MQTT 6.0.3

https://github.com/zwave-js/node-zwave-js/releases/tag/v8.8.3

The current addon version of zwavejs2mqtt contains the older version of zwavejs2mqtt with the underlying zwavejs bugs and needs to be updated to the latest stable release of zwavejs2mqtt 6.0.3

## Expected behavior

Stable zwave network without crashing

## Actual behavior

network crashes due to bugs mentioned above

## Steps to reproduce

Steps are well documented in the corresponding github issues and community forum link above.  Generally, the network fails when multiple commands are sent to the Zwave network at once (IE a "goodnight" shutoff/lock routine) 

## Proposed changes

This has already been fixed in the latest stable release of zwavejs2mqtt, and the new release https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v6.0.3 just needs to be pulled into the addon version.

**Comment by johanschelin** [comment]
Yes please release this as soon as possible! :)

**Comment by frenck** [comment]
Done already in #307, cannot release right now, as GitHub Actions is down.
Will be done as soon as their return in service.
