### ISSUE TITLE
Network restarting with openssl error

### ISSUE THREAD

**Issue by shaneprice** [hassio-addons/addon-zwavejs2mqtt#309]
# Problem/Motivation

> A few days ago all of my zwave devices became unresponsive, trying to access the webUI failed so I went into supervisor and can see it looks like it crashing and restarting.

## Expected behavior

Have access to the Z-Wave JS to MQTT Web UI

## Actual behavior

My logs are getting flooded with 

2021-12-04 13:27:19.300 WARN STORE: scenes.json not found
2021-12-04 13:27:19.307 INFO APP: HTTPS is enabled. Loading cert and keys
2021-12-04 13:27:19.308 INFO APP: Cert and key not found in store, generating fresh new ones...
Error: Could not find openssl on your system on this path: openssl
    at /opt/node_modules/pem/lib/openssl.js:237:23
[13:27:19] INFO: Starting the Z-Wave JS to MQTT...
[13:27:19] TRACE: bashio::net.wait_for 3000 localhost 1800

## Steps to reproduce

I dont actually know. Prior to seeing this issue my last update of the zwavejs2mqtt was a couple of weeks ago. Sorry if this is a vague question but I am a little unsure where to look to try troubleshoot this myself

**Comment by N3rdP1um23** [comment]
I also experience this issue after the recent 0.31.1 update that was published yesterday. I had initially setup zwavejs2mqtt the day prior without issue, once the autoupdate finished, I am receiving the same issue and it seems to be suck in a constant loop. Opening the Z-Wave JS side bar results in a 502 error both with the local and remote Home Assistant paths.

In my Supervisor system logs, I also see the following which is also stuck in a loop.
```
21-12-04 14:16:48 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.0:8099 ssl:default [Connect call failed ('172.30.33.0', 8099)]
21-12-04 14:17:53 WARNING (MainThread) [supervisor.misc.tasks] Watchdog missing application response from a0d7b954_zwavejs2mqtt
21-12-04 14:19:53 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with a0d7b954_zwavejs2mqtt application!
21-12-04 14:19:53 INFO (SyncWorker_1) [supervisor.docker.interface] Stopping addon_a0d7b954_zwavejs2mqtt application
21-12-04 14:19:58 INFO (SyncWorker_1) [supervisor.docker.interface] Cleaning addon_a0d7b954_zwavejs2mqtt application
21-12-04 14:19:59 INFO (SyncWorker_5) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/zwavejs2mqtt/amd64 with version 0.31.1
```


I've attempted restarting the host, core, and supervisor with no luck.

**Comment by N3rdP1um23** [comment]
I've dug into it a little more and was able to find the following info

When running an interactive shell with the add-on docker container, the following errors are dumped to the console
![image](https://user-images.githubusercontent.com/8093806/144752182-590acec0-000e-4803-be65-c468fb97f536.png)
After this, it goes into a loop of attempting to connect and then retrying connection again in 3 seconds. Also, the proxy_pass_header error.

While looking at the proxy_pass_header, the following is the contents of the `/etc/nginx/servers/ingress.conf` file
![image](https://user-images.githubusercontent.com/8093806/144752259-922c4815-a416-41ac-b29c-48433280450b.png)
Not sure if that needs to be explicitly set here for this add-on or not.

After commenting out the `proxy_pass_header` in the `ingress.conf` file, the nginx emerg errors disappear and only the ZWAVE errors exist
![image](https://user-images.githubusercontent.com/8093806/144755738-0a8743d0-96f6-4e35-a773-bf46606c91f6.png)


----

In the first screenshot, it mentions `Controller status: Driver: "path" is not defined:` and looking online it seems that other users have mentioned that it may be related to the path of the zwave USB and the driver not finding it. Everything seems to be okay, and the USB is mounted and can be found inside HASSIO. From here, it looks like it kicks off the endless loop of attempting to connect and failing.

----

I also see the following when viewing the **Z-Wave JS** integration configuration
![image](https://user-images.githubusercontent.com/8093806/144768122-eebfc6c3-8c1a-4e23-ad09-3a54b43e95c6.png)

Hopefully that helps narrow down the issue a little more. If there's anything else I can grab, feel free to let me know!

**Comment by shaneprice** [comment]
I ended up just uninstalling the addon and reinstalling. A real shame as the addon is working again however I have lost all the names from the addon and home assistant

**Comment by N3rdP1um23** [comment]
My apologies for the late response. When I was trying to replicate the issue in a dev instance of HA and accidentally ended up nuking my main HA instance. Thankfully, I was just starting out, so it was easy to get everything back.

After setting everything up again, zwavejs2mqtt is working without an issue and I'm no longer experiencing this issue.

**Comment by momoz** [comment]
I have this exact issue today.  Can't figure out what to do!

**Comment by 410sean** [comment]
same issue i reproduce by starting a fresh install, in settings under general i enable https. restart container and it will go into an unending loop.

resolution for now is to uninstall and then reinstall. this does prevent me from using some features of smart start if i cannot use https

**Comment by momoz** [comment]
I had this same issue and was able to restore from a backup to before I set the HTTPS option in the settings.   I enabled HTTPS so I could scan QR for SmartStart and that update broke this.  I have had zero problems since with HTTPS being unchecked, but I can not use SmartStart Scan feature.

**Comment by dkmcgowan** [comment]
this happened to me as well, you can ssh into your hass instance, then find the container as it's looped with docker ps, then you can use "docker exec -it container_id bash" and get into the container, then "vi /data/store/settings.json" then search for http and change true to false, save, restart, and your back...  it should be moved to the add-on configuration page and then allowed to specify where to load the pem files

**Comment by galenemery** [comment]
Im also running into this issue.  Looks like the haos does not ship with openssl, so this issue exists when attempting to enable https?

**Comment by galenemery** [comment]
So, compared to the `zwavejs2mqtt` repo's dockerfile, I don't see that this one is adding openssl anywhere.

https://github.com/zwave-js/zwavejs2mqtt/blob/master/docker/Dockerfile#L52

versus

https://github.com/hassio-addons/addon-zwavejs2mqtt/blob/main/zwavejs2mqtt/Dockerfile#L20-L24

Is there a reason that change never made it to the add-on based image?

**Comment by boostin4hp** [comment]
I just got this EXACT same issue after doing a update today. I did try to enable SSL like a month ago but was given a warning and disabled it. I've restarted many time since then and am curious why it would now enable SSL after updating? I am running a virtual box vm and cannot access the settings.json file as described by dkmcgowan can some please advise me on opening it?

**Comment by boostin4hp** [comment]
> this happened to me as well, you can ssh into your hass instance, then find the container as it's looped with docker ps, then you can use "docker exec -it container_id bash" and get into the container, then "vi /data/store/settings.json" then search for http and change true to false, save, restart, and your back... it should be moved to the add-on configuration page and then allowed to specify where to load the pem files

This just happened to me after a update today. What’s the easiest way to get the container ID on a virtual box VM running on a Windows 10 pc? I have physical access and also SSH. All the commands I’ve tried don’t work.

**Comment by waynehead99** [comment]
I am seeing this same issue after the most current core and OS update. I am trying to set it back to HTTP to at least get back to the screen and can't see to find the proper way to actually get into the docker its running in. 
I am also running this as a VM on a windows 10 machine

**Comment by boostin4hp** [comment]
After hours of messing with this I was able to get it back up using the following steps.

[dkmcgowan] gave most of the steps but there was a few more (https://github.com/dkmcgowan)https://github.com/hassio-addons/addon-zwavejs2mqtt/issues/309#issuecomment-1051342300

I was running a virtualbox vm and didn't have host ssh access until I install the SSH & Web Terminal addon and disabled protected mode. Then I had full access to the docker and could get the container ID and edit settings.json

I was able to get into the zwavejs2mqtt web ui now but it was completely blank because it couldn't connect to my zstick7. After verifying the settings what finally worked was actually restarting the host computer not just the VM. Then everything was back up and running.

**Comment by rossco555** [comment]
> this happened to me as well, you can ssh into your hass instance, then find the container as it's looped with docker ps, then you can use "docker exec -it container_id bash" and get into the container, then "vi /data/store/settings.json" then search for http and change true to false, save, restart, and your back... it should be moved to the add-on configuration page and then allowed to specify where to load the pem files

Hi dkmcgowan, could you please help me with this? I have Home Assistant installed as a docker container on a Synology NAS, with zwavejsmqtt in another container. I stupidly enabled SSL and now can't get into zwavejs2mqtt. How do I manually revert that config? I have a environment variable in my docker-compose `ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db` but that was just a copy-paste from an online guide so I have no idea where it actually exists.

**Comment by jeffdoubleyou** [comment]
This is still a problem, why is this closed?

**Comment by DavidRBailey** [comment]
This needs to be reopened. It is still a problem.
