### ISSUE TITLE
Retrying setup: Z-Wave JS Server version is incompatible: 1.11.0 a version is required that supports at least api schema 12

### ISSUE THREAD

**Issue by danielbrunt57** [hassio-addons/addon-zwavejs2mqtt#310]
# Problem/Motivation

> Just updated to HA 12.1 and now Z-Wave Integration is complaining

## Expected behavior

> No errors!

## Actual behavior

> Z-Wave JS Integration is failing and I have no Z-Wave devices in HA...

## Steps to reproduce

> Use Z-Wave JS to MQTT Add-on (Current version: 0.30.0), Z-Wave JS Integration and HA 12.1

## Proposed changes

> ???

![image](https://user-images.githubusercontent.com/49846893/145779158-4ca0902d-4b87-4c30-b657-81bd99cb8399.png)

**Comment by bkcsoft** [comment]
~~I'm seeing the same things (on HA `2021.12.1`) as well. Addon is version `0.30.0`, I see here that the latest is `0.31.1`.~~

Had just about debugged it when HA Addon-page started listing community addons again and suggested the update to `0.31.1`.

After the update it working again :shrug:

**Comment by frenck** [comment]
The current latest version of the add-on is v0.31.1

https://github.com/hassio-addons/addon-zwavejs2mqtt/releases/tag/v0.31.1

You'll need to update the add-on to match Home Assistant (the latest).

**Comment by danielbrunt57** [comment]
Why am I not being offered 0.31.1??

![image](https://user-images.githubusercontent.com/49846893/145856938-dd99c710-38a3-4b60-89c2-0552dececf88.png)

**Comment by frenck** [comment]
I dunno?

**Comment by danielbrunt57** [comment]
Any technical insight into how that process works?

**Comment by frenck** [comment]
It publishes a meta file with the configuration and version information to the add-on repository that your Home Assistant downloads:

<https://github.com/hassio-addons/repository/blob/master/zwavejs2mqtt/config.yaml#L32>

**Comment by TheDK** [comment]
Maybe try a restart of the Addon or the Supervisor?

**Comment by danielbrunt57** [comment]
I am using these add-on's but more than half of them are not listed in the add-on store?

![image](https://user-images.githubusercontent.com/49846893/145860983-37588f2b-5636-48eb-8c69-f188090f3b6f.png)

![image](https://user-images.githubusercontent.com/49846893/145861063-ee0599d4-8a05-4f6d-a7a6-1d021520825d.png)

I am puzzled...

**Comment by danielbrunt57** [comment]
I've restarted the add-ons as well as the entire host...

**Comment by frenck** [comment]
Seems like you have removed the community store.

Use the tree-dotted menu in the top right to add an add-on repository and add:

`https://github.com/hassio-addons/repository`

**Comment by dattas** [comment]
I also had this issue, there is likely a bug in supervisor or homeassistant that removes that repository. I did not remove that and my home assistant is not exposed to the outside.

**Comment by danielbrunt57** [comment]
I didn't remove it but adding it fixed the issue, thanks.  I also now see updates for ESP-Home, Node-RED and UniFi...
I would appear to not be alone...
https://community.home-assistant.io/t/zwavejs-incompatible-version/366164/8

**Comment by raidenlal** [comment]
This should be really more promoted. Repository was deleted for me as well.

**Comment by mikejgray** [comment]
Same.

**Comment by tokyotexture** [comment]
Same here. Zwave was broken with the update, and this was the cause..

**Comment by danielbrunt57** [comment]
> Same.
Solved now??

**Comment by StarFox2873** [comment]
Same issue I did not remove the repo, re adding it allowed me to I need to upgrade the zwave js addon.
