### ISSUE TITLE
After upgading HA to 2021.12.2, HA gives retrying setup: z-wave js server version is incompatible: 1.10.4 a version is required that supports at least api schema "12"

### ISSUE THREAD

**Issue by dmshimself** [hassio-addons/addon-zwavejs2mqtt#315]
# Problem/Motivation
After upgrading HA (using hassos) to 2021.12.2, the zwave integration gives the error
home assistant retrying setup: z-wave js server version is incompatible: 1.10.4 a version is required that supports at least api schema "12"

## Expected behavior
zwavejs2mqtt to support for the required API level

## Actual behavior
The zwave-js integration doesn't complete its setp, but gives this error instead

## Steps to reproduce
In my case have a 2011.x install with zwavejs2mqtt installed and upgrade to 2012.2

## Proposed changes

Support for later API version.  In th meantime, I've done a temp setup of another zwave-js server on a new VM with the latest verion and that works just fine.  Docker install decribed here:
https://zwave-js.github.io/zwavejs2mqtt/#/getting-started/docker

**Comment by frenck** [comment]
> In my case have a 2011.x install with zwavejs2mqtt installed and upgrade to 2012.2

Are you using the add-on or a Docker install?

**Comment by frenck** [comment]
You need to install the latest version of the add-on: v0.32.0
(although v0.31.1 will work as well).

https://github.com/hassio-addons/addon-zwavejs2mqtt/releases/tag/v0.32.0

**Comment by dmshimself** [comment]
0.32 worked very well
