### ISSUE TITLE
zwavejs2mqtt 6.1.x uses a beta version of node-zwave-js 8.9.0 that has problems with S2

### ISSUE THREAD

**Issue by mundschenk-at** [hassio-addons/addon-zwavejs2mqtt#318]
# Problem/Motivation

The beta version of node-zwave-js (8.9.0betaX) used in zwavejs2mqtt 6.1.x has some serious stability issues with S2 security. I was surprised that the addon is using that driver version.

## Proposed changes

Since downgrading addons is rather difficult, I suggest reverting back to zwavejs2mqtt 6.0.x.

**Comment by frenck** [comment]
The add-on is not using it, is Zwavejs2Mqtt, which this add-on uses.
`Zwavejs2Mqtt` has released it as stable.

Please report this issue with the Zwavejs2Mqtt project.

https://github.com/zwave-js/zwavejs2mqtt/
