### ISSUE TITLE
Version 0.32.2 not published

### ISSUE THREAD

**Issue by mundschenk-at** [hassio-addons/addon-zwavejs2mqtt#320]
# Problem/Motivation

The publish action after the recent release of zwavejs2mqtt 0.32.2 failed in both repositories (probably due to GH issues at the time). While the release action itself was restarted and eventually succeeded, the publish workflows have not been, preventing the new add-on release from being published.

Follow-up to https://github.com/hassio-addons/repository/issues/365

## Proposed changes

The zwavejs2mqtt 0.32.2 should be published to the add-on repositories.

**Comment by frenck** [comment]
This is caused by a GitHub outage, which has been resolved just a moment ago.

**Comment by frenck** [comment]
I've retriggered the release flow:

![image](https://user-images.githubusercontent.com/195327/147497129-4a7b0359-967e-4582-8782-eddb6b1660e9.png)

Hopefully, it passes now 🙏

**Comment by frenck** [comment]
Done 👍

**Comment by mundschenk-at** [comment]
Thank you! I am already installing the new version 😀
