### ISSUE TITLE
0.32.2 asleep / awake loop

### ISSUE THREAD

**Issue by acburnett** [hassio-addons/addon-zwavejs2mqtt#321]
# Problem/Motivation

> After updating to 0.32.2, my zwave network stopped working. The logs show an awake / asleep loop for a smoke detector that is definitely asleep. Its a first alert zcombo and they rarely wakeup. I have 5 of them and only the one is logged in the loop, rolling back to 0.32.1 fixed the issue. 

## Expected behavior

> The zwave network wouldnt be flooded with a constant awake / asleep loop, flooding the logs and causing it to be unresponsive.

## Actual behavior

> unable to control any devices on zwave network

## Steps to reproduce

> Im not sure, hopefully im not the only one that had the issue and someone much smarter than me could chime in. 

## Proposed changes

> Going back to 0.32.1 fixed it for me

![Screenshot_20211227-154323_Home Assistant](https://user-images.githubusercontent.com/26014123/147527908-92b16e29-abd5-49a4-ac3b-1f956cb9166b.jpg)

**Comment by jasonshearer** [comment]
I am having the same issue after upgrading to 0.32.2 running on a Zooz S2 USB stick. Nodes are showing available in the console but no devices respond to commands.

**Comment by jparchem** [comment]
0.32.2 is also causing issues for me.  I'm unning on a Nortek GoControl ZWave/Zigbee combo stick.  On 0.32.1 all was good, but once I updated to 0.32.2 all of my Z-Wave devices show online but do not respond to commands.  Same as @jasonshearer I restored 0.32.1 from backup and everything is working again.

**Comment by TheDK** [comment]
Is a Re-Interview possible and does it change anything?

**Comment by momoz** [comment]
I’ve had the same problem on the last two versions.  I’ve restored function by restarting and triggering zwave switch manually.  Seems it works for a few hours or day and fails again to interact with zwave network

**Comment by jasonshearer** [comment]
> Is a Re-Interview possible and does it change anything?

I tried a soft reset of the controller and a heal. Neither had an effect on restoring functionality of the network.

**Comment by TheDK** [comment]
> > Is a Re-Interview possible and does it change anything?
> 
> I tried a soft reset of the controller and a heal. Neither had an effect on restoring functionality of the network.

That is not an answer to my question. :)

**Comment by frenck** [comment]
So, this is in the wrong place.
This is an issue with Zwavejs2Mqtt itself, not the add-on.

Please report this upstream. Thanks! 👍

**Comment by jasonshearer** [comment]
@acburnett - I scrubbed the issues and didn't see anything similar. I can copy/paste the issue or you can.

https://github.com/zwave-js/zwavejs2mqtt/issues

**Comment by acburnett** [comment]
Thank you all, @jasonshearer if you are able to id appreciate it. Otherwise i will post on theirs after work today.

**Comment by kpine** [comment]
The awake / asleep loop problem reported by OP is fixed in zwave-js 8.9.2. There isn't a z2m release yet with this driver version. As a workaround, you can manually wake up the ZCOMBO (pull batteries, hold test button, re-insert batteries) and it will fix the problem.
