### ISSUE TITLE
32.1 and 32.2 issues with Sensative strips guard 700

### ISSUE THREAD

**Issue by h-parks** [hassio-addons/addon-zwavejs2mqtt#322]
# Problem/Motivation

S2 door/window sensors show "open" but then fail to show "closed" after upgrading to 32.1 and behavior remains after 32.2.

(opens)
`2021-12-28 22:44:34.159 INFO ZWAVE: Node 57: value updated: 113-0-Access Control-Door state 23 => 22`

(closes)
`INFO ZWAVE: Node 57: value updated: 113-0-Access Control-Door state 22 => 23`

## Expected behavior

Sensors show "closed" after a door or window closes.

## Actual behavior

Sensor remains 'open' and value does not change. 

## Steps to reproduce

Alternate between 31.1 and 32.1/32.2 ZwaveJS2Mqtt installs.

[zwavejs2mqtt_2021-12-28.log](https://github.com/hassio-addons/addon-zwavejs2mqtt/files/7787456/zwavejs2mqtt_2021-12-28.log)

**Comment by frenck** [comment]
This is not an issue with the add-on, but with the upstream ZwaveJS2Mqtt this project wraps.

Please report this issue with the ZwaveJS2Mqtt project.
