### ISSUE TITLE
Automation failed due to capital leeter used on climate entities

### ISSUE THREAD

**Issue by mainate** [hassio-addons/addon-zwavejs2mqtt#324]
# Problem/Motivation

When I set condition in automation for a climat device (Qubino) I always fget false result.

## Expected behavior
My automation condition is set as :
condition:
  - condition: device
    device_id: xyz
    domain: climate
    entity_id: climate.corridor_etage_2
    type: is_hvac_mode
    hvac_mode: 'off'

and when hvac_mode is 'off' I expect to have a "true" result

## Actual behavior

The result of the condition is always off

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

Use off or heat info without capital letters!

**Comment by frenck** [comment]
This is not rated to the add-on, but Home Assistant itself.

Therefore you are in the wrong issue tracker.
