### ISSUE TITLE
Error: external_convertrers not found

### ISSUE THREAD

**Issue by petervandervoort1953** [hassio-addons/addon-zwavejs2mqtt#329]
I'm fairly new to Home-Assistant.
My Configuration RP4, core-2021.12.3 and Home-Assistant OS 6.6

To be able to use z-wave smoke detection sensors (Heiman HS1SA-Z) I used a Z-Stick Gen5 USB controller.
In HA i installed the Add-on 'Z-Wave JS to MQTT' and the integration Z-Wave JS  and i have the Mosquitto broker added. 
After configuration, the Z-stick is recognized. 

Also, after coupling the Z-stick with the smoke detector, the detector is shown, but without any further information and signaling. 
The Heiman detector device is not in the list of preconfigured devices.
I followed [this document](https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html#instructions) to add a deviceconfiguration for this detector,  i created a devicefile (hs1sa_z.js), and modified configuration.yaml.

![afbeelding](https://user-images.githubusercontent.com/68079023/148701205-e93b76d4-5ee7-45ee-9cc2-27bc343ea2ab.png)

Using Settings-Server Manager 'Configuration Validation' I received these messages: 
_Integration error: advanced - Integration 'advanced' not found. 
Integration error: external_converters - Integration 'external_converters' not found._ 

It is clear that there is missing something, maybe something like the zigbee-herdsman-convertors.
I did not find any information further about this kind problems.

What should I need to install or change and how should I do that? 
I cannot find someting like rpm or ntm or another install tool.

Please leave a comment.

**Comment by sinclairpaul** [comment]
The link you added was for the Zigbee2MQTT application.

The documentation for the application that this addon packages is at https://zwave-js.github.io/zwavejs2mqtt/#/

**Comment by frenck** [comment]
Closing, mixup of applications.
