### ISSUE TITLE
0.33.0 breaks zwave entities in HA

### ISSUE THREAD

**Issue by teknomar7** [hassio-addons/addon-zwavejs2mqtt#332]
# Problem/Motivation

When upgrading the add-on to 0.33.0, I have a number of zwave lights that show as grayed out in my dashboard and some switches that are showing as entity not available.  Restarting HA does not solve the issue.  I am only able to solve it when doing a full restore to a backup (rolling back to the previous version of the addon doesn't work by itself).  The devices still seem to show up correctly and working in the zwave controller, but it seems something breaks the integration with HA entities.  I've updated this addon many times in the past without this issue, and I've replicated the issue by rolling back and updating again with the same results.  I can provide additional information or logs if necessary... I just don't know what would be useful for this issue.

## Expected behavior

Upgrading addon doesn't change any functions in the dashboard.

## Actual behavior

Some light entities are showing grayed out and some switch entities are showing entity not available.

## Steps to reproduce

Upgrade from 0.32.2

## Proposed changes

N/A

**Comment by Steven4x4** [comment]
Same issue here.
What I discovered was that any entity that had a underscore in the name was replaced.

**Example:**
switch.kitchen_cabinet_light
  CHANGED TO
switch.kitchencabinetlight

Its almost like it deleted the originally entity and created a new one as any other configurations like predefined icons were also lost.

**Comment by teknomar7** [comment]
Same issue in 0.34.0.  I just ended up fixing it manually (thanks @Steven4x4).  I just renamed my entities in HA that went missing.  Most of them were something that was switch.kitchen_sink before, then got renamed switch.sink after the update for some reason.

**Comment by Steven4x4** [comment]
@teknomar7 that's what I was thinking too, but I realized I have about 20+ entities like that, and I wasn't sure if I'd have to go into all of my automation and fix those as well.

Thank you @frenck. I figured something would be released soon. 
I appreciate all of you've done for this community!

**Comment by Steven4x4** [comment]
Confirmed - After Upgrading the HA Core to 2022.12.10 (Released today). 
I was then able to successfully upgrade to ZwaveJSMQTT to 0.34.0.

**Comment by teknomar7** [comment]
Also works with my manual correction without causing any new problems.  Closing the issue.  Thanks.
