### ISSUE TITLE
Watchdog makes the add-on restart every ~5minutes

### ISSUE THREAD

**Issue by sanderegg** [hassio-addons/addon-zwavejs2mqtt#338]
# Problem/Motivation
I have the zwavejs2mqtt add-on running on 2 different instances of Home-Assistant supervised.
Today I found out that the add-on was restarting more or less every 5 minutes with the following error message in its logs:
```console
2022/01/19 19:45:30 [error] 432#432: *2 access forbidden by rule, client: 172.30.32.1, server: a0d7b954-zwavejs2mqtt, request: "GET /health/zwave HTTP/1.1", host: "172.30.33.2:8099"
2022-01-19 19:45:30.531 WARN APP: Shutdown detected: closing clients...
2022-01-19 19:45:30.532 INFO GATEWAY: Closing Gateway...
2022-01-19 19:45:30.550 INFO ZWAVE-SERVER: Server closed
2022-01-19 19:45:30.555 INFO ZWAVE-SERVER: Client disconnected
2022-01-19 19:45:30.586 INFO ZWAVE: Client closed
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing...
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

Disabling the Watchdog function in home-assistant add-on menu fixes the problem but then in case of a real failure the add-on will not restart.

I am using:
```
Z-Wave JS to MQTT
Current version: 0.34.1
```
together with home-assistant ```2021.12.5```
and
```
Z-Wave JS to MQTT
Current version: 0.33.0
```
together with home-assistant ```2021.12.2```
both have the issue.
I cannot say when this started to happen.

> (Why the issue was filed)

## Expected behavior

The watchdog function should only restart the add-on if the add-on is somehow stuck and not responding correctly to the healthcheck.

> (What you expected to happen)

## Actual behavior

The ```zwavejsmqtt``` module restarts every 5 minutes, thus my zwave devices are unavailable for 20 seconds every 4-5 minutes. Thus the history of any z-wave device is like this:
![image](https://user-images.githubusercontent.com/35365065/150195670-8f0c8284-3f42-471a-8b0c-313c030ce18e.png)

> (What actually happened)

## Steps to reproduce
1. Install the zwave-js2-mqtt add-on
2. in the add-one properties, switch on the watchdog feature
3. wait for about 4-5 minutes and the container will be restarted, wait again about 4-5 minutes, ... and so on...
> (How can someone else make/see it happen)

## Proposed changes
Fix the healtchcheck entrypoint or explain me how I should configure the add-on so that this does not happen.

Also thanks a lot for this amazing plugin and the whole home-assistant framework, it is really amazingly cool!
> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sanderegg** [comment]
well actually... after looking into the issue for several days I actually found it is on my end.
I did fiddle with iptables to make home-assistant available through wireguard and it seems this add-on does not like my settings.
Sorry for the spam, I'll close that issue.

**Comment by frenck** [comment]
Don't worry! Glad you got it figured out 👍
