### ISSUE TITLE
Feature Request: Automatically Ping Dead or Unknown Nodes

### ISSUE THREAD

**Issue by harryfrishberg** [hassio-addons/addon-zwavejs2mqtt#341]
# Problem/Motivation
I have been experiencing a higher than usual occurrence of the "unknown" status on various Z-Wave nodes. 99% of the time, this problem is immediately fixed by running the ping command. But with 50+ devices, it becomes a daily chore. I have tried healing the network, re-interviewing frequent offenders, but nothing seems to work. 

## Proposed changes
If possible, could an optional function be added to ping or poll any nodes that have become "unknown" or otherwise unresponsive until they become "alive" again? After a set amount of time, if no response is heard, the devices can be marked as "dead". 

---

PS - I've attempted to create a Home Assistant automation with this functionality, but my knowledge of scripting is subpar and I can't seem to get it working. In case anyone can spot an error in my ways, here is the automation:

- id: 'xxxxxxxxxxx'
  alias: Red October
  description: Pings any dead or unknown nodes on Z Wave Network until a response is heard
  trigger:
  - platform: event
    event_type: state_changed
  condition:
  - condition: and
    conditions:
      - condition: template
        value_template: '{{ trigger.event.data.new_state.domain == "sensor, switch, lock, light" }}'
      - condition: template
        value_template: '{{ trigger.event.data.new_state.state == "dead, unavailable, unknown, none" }}'
  action:
  - repeat:
      until:
        - condition: template
          value_template: '{{ trigger.event.data.new_state.state == "alive" }}'
      sequence:
        - service: zwave_js.ping
          target:
            entity_id: '{{ trigger.entity_id }}'
        - delay:
            hours: 0
            minutes: 1
            seconds: 0
            milliseconds: 0
  mode: parallel
  max: 5

**Comment by frenck** [comment]
This is not a feature request the add-on can do anything about.

Add-ons wrap existing applications, in this case: The Zwavejs2Mqtt project.
If they add features like those, it would automatically end up in the add-on.

Please request this feature with the project upstream.

Thanks! 👍

**Comment by harryfrishberg** [comment]
My mistake! Thanks for clarifying!
