### ISSUE TITLE
Control Panel does not load devices list

### ISSUE THREAD

**Issue by dkmcgowan** [hassio-addons/addon-zwavejs2mqtt#347]
# Problem/Motivation

The control panel does not always load the devices list.  I sometimes I have to click to load it 10+ times.  It will always load if I clear cache or run in an incognito window.  I do not see any console errors when it's not loading the list.  It does turn green and show connected, just nothing shows up in the device list.  There are no issues, devices and server is running fine, seems to just be the UI.

zwavejs2mqtt: 6.5.2
zwave-js: 8.11.6

Home Assistant 2022.2.9

It does it on the mobile app on Android and my laptop in Chrome and Firefox.

My Hass is running behind HAProxy, but not having any other issues with it or if that is relevant.

> (Why the issue was filed)

## Expected behavior

Load everytime

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by dkmcgowan** [comment]
When it doesn't load the list you do not see the message in the logs "Event INITED emitted to", when it works, you do see that message

**Comment by TheDK** [comment]
I have noticed this regularly - more on iOS devices through companion app or safari, less often on Win10 with FF / Chrome. Some reloading mostly helps…
