### ISSUE TITLE
Need way to do health check w/ add-on

### ISSUE THREAD

**Issue by johntdyer** [hassio-addons/addon-zwavejs2mqtt#35]
# Problem/Motivation

Looking for a health check so an external monitor can tell if the driver is up

## Expected behavior

port 8091 isnt exposed so I cant use the official one

## Actual behavior

n/a

## Steps to reproduce

n/a

## Proposed changes

I think just exposing port 8091 may allow me to use the curl check

```
curl http://192.168.100.16:8091/health/zwave -H "Accept: text/plain"
```

**Comment by frenck** [comment]
You can't use this add-on from an external monitor, it relies on Ingress.
