### ISSUE TITLE
wrong changelog

### ISSUE THREAD

**Issue by strelniece** [hassio-addons/addon-zwavejs2mqtt#351]
Hi,

seems like the changelog for 0.36.0 is the same as for the Node-red 11.1.0 one, No major changes I hope :)

**Comment by strelniece** [comment]
Ok, just thought it weird when the changelog says:
Upgrades add-on base image to 11.1.0 @frenck (#348) , I thought it would be 0.36.0 for zwavejs2mqtt.

**Comment by frenck** [comment]
Its the base image... 

https://github.com/hassio-addons/addon-base/releases/tag/v11.1.0
