### ISSUE TITLE
Dark mode issue

### ISSUE THREAD

**Issue by artlov** [hassio-addons/addon-zwavejs2mqtt#356]
# Problem/Motivation

Dark mode selected, but not applied after opening add-on GUI

## Expected behavior

Dark mode applied after enterting into GUI

## Steps to reproduce

Just go into GUI - it opened in white. 
![image](https://user-images.githubusercontent.com/6746304/160095114-122a705a-e81e-45fe-81a7-84c089fc3ea2.png)

After clicking to any other tab dark theme applied.
![image](https://user-images.githubusercontent.com/6746304/160095190-8b31c78b-c738-436a-982a-4a9fe659190b.png)

zwavejs2mqtt: 6.6.0
zwave-js: 8.11.9

**Comment by AlanGreene** [comment]
This is fixed in zwavejs2mqtt 6.6.1 which was merged in https://github.com/hassio-addons/addon-zwavejs2mqtt/pull/355

Looks like we just need a release 🤞 🙏 @frenck

**Comment by frenck** [comment]
> anything I can do to help move this along

have patience.
