### ISSUE TITLE
Aeon Gen5 USB adapter in docker fails after some time

### ISSUE THREAD

**Issue by sujitvasanth** [hassio-addons/addon-zwavejs2mqtt#357]
I have switched recently from smartthings and zigbee2mqtt works great without problems

I had problems using zwave2mqtt where my zwave devices stopped responding after a few minutes but worked again if I restarted the service and hard reset the USB adapter.

The setting to disable soft resets to the adaptor fixed the problem - surely you can set this by default for docker installations

**Comment by frenck** [comment]
> The setting to disable soft resets to the adaptor fixed the problem - surely you can set this by default for docker installations

No, it cannot be set to that by default. The current default works fine for most use cases.

Nevertheless, you can change it if fits your case better.

../Frenck
