### ISSUE TITLE
sidebar incorrectly labelled

### ISSUE THREAD

**Issue by sujitvasanth** [hassio-addons/addon-zwavejs2mqtt#358]
Sidebar option in zwave js 2 mqtt is incorrectly labelled as 'Z-wave JS' but should be 'zwavejs2mqtt'

**Comment by frenck** [comment]
It should be "Z-Wave JS to MQTT" actually as that is the name of the add-on; which doesn't fit in the sidebar.

Anyways, I'm not adjusting this for that reason. Nevertheless, thanks for the feedback 👍
