### ISSUE TITLE
No update to 0.39 available

### ISSUE THREAD

**Issue by pschyrembel258** [hassio-addons/addon-zwavejs2mqtt#367]
I'm still on 0.37 and there is no update option. How can I force the search for the update?

**Comment by Amishman** [comment]
I am also having this issue.

**Comment by HVR88** [comment]
"Auto Update" hasn't done anything on my system and I'm also still on 0.37.0 of the add-on ( "6.6.0" )

**Comment by asucher** [comment]
I am also having this issue.

**Comment by frenck** [comment]
0.39.0 is available, see also here: <https://github.com/hassio-addons/addon-zwavejs2mqtt/releases>

Be sure you have the community add-ons store installed on your system. If not, you can use this button to (re-)add it.

[![Open your Home Assistant instance and show the add add-on repository dialog with a specific repository URL pre-filled.](https://my.home-assistant.io/badges/supervisor_add_addon_repository.svg)](https://my.home-assistant.io/redirect/supervisor_add_addon_repository/?repository_url=https%3A%2F%2Fgithub.com%2Fhassio-addons%2Frepository)
