### ISSUE TITLE
No update after 0.37.0

### ISSUE THREAD

**Issue by jwagner0789** [hassio-addons/addon-zwavejs2mqtt#368]
I feel like I'm missing something but I just can't get this add-on to update past 0.37.0. I went to update HA to 2022.5 today but saw the breaking changes required me to update this add-on first. I enabled auto update to see if it would update for me but no luck. Ideas?

**Comment by sinclairpaul** [comment]
Please see #367

**Comment by jwagner0789** [comment]
Come to find out AdGuard was the reason. Also, found that it was the reason my entire network would drop randomly. Safe to say AdGuard is gone and I was able to update this add-on and a few others. Thanks for the help.
