### ISSUE TITLE
502 Bad Gateway after Update and all devices are unavailable.

### ISSUE THREAD

**Issue by boostin4hp** [hassio-addons/addon-zwavejs2mqtt#379]
# Problem/Motivation

After updating to the new version 42 all devices are unavailable and I can't access the web ui, it returns a "502 bad request" error. It appears SSL has been turned on after the update since it states it in the log and is the EXACT same symptoms as described in issue #309 https://github.com/hassio-addons/addon-zwavejs2mqtt/issues/309

## Expected behavior

To update and be fine

## Actual behavior

[log.txt](https://github.com/hassio-addons/addon-zwavejs2mqtt/files/8801281/log.txt)

## Steps to reproduce

By turning on SSL

## Proposed changes

A way to disable SSL outside of the Web UI since it no longer works.

**Comment by boostin4hp** [comment]
After hours of messing with this I was able to get it back up using the following steps.

[dkmcgowan] gave most of the steps but there was a few more (https://github.com/dkmcgowan)https://github.com/hassio-addons/addon-zwavejs2mqtt/issues/309#issuecomment-1051342300

I was running a virtualbox vm and didn't have host ssh access until I install the SSH & Web Terminal addon and disabled protected mode. Then I had full access to the docker and could get the container ID and edit settings.json

I was able to get into the zwavejs2mqtt web ui now but it was completely blank because it couldn't connect to my zstick7. After verifying the settings what finally worked was actually restarting the host computer not just the VM. Then everything was back up and running.

**Comment by TheDK** [comment]
Just for clarification: Did you explicitly turn on SSL before running into or did that happen by itself as part of the update (so was the switch flicked in the config part of the GUI)? For updating to 2022.6 of HA this needs to be updated as well, so I try to get a feeling of what I am getting myself into...

**Comment by boostin4hp** [comment]
I had flipped the SSL switch about a month ago but was shown a warning so I immediately disabled it again. I’ve restarted multiples times since then due to other upgrades or my own changes but for some reason when I updated to 42 the HTTPS: true stuck apparently.
