### ISSUE TITLE
On HA 2022.6.0 - no more data passed from addon to HA

### ISSUE THREAD

**Issue by Masterz69** [hassio-addons/addon-zwavejs2mqtt#380]
# Problem/Motivation

After HA upgrade to 2022.6.0 - no more data in HA from ZWave JS 2MQTT add-on.
No data from sensors, NOTHING.

Add-on itselves looks fine, all devices online, data arrives, but n passed to HA.
```
2022-06-02 10:57:14.368 INFO ZWAVE: Node 5: value updated: 50-0-value-65537 1383.59 => -21473452.87
2022-06-02 10:57:14.460 INFO ZWAVE: Node 5: value updated: 50-0-value-66049 74.21 => 73.91
2022-06-02 10:57:14.549 INFO ZWAVE: Node 5: value updated: 50-0-value-66561 241.05 => 241.09
2022-06-02 10:57:14.640 INFO ZWAVE: Node 5: value updated: 50-0-value-66817 0.58 => 0.58
2022-06-02 10:57:16.015 INFO ZWAVE-SERVER: Client disconnected
```
ZWave JS 2MQTT version 0.39.0

## Expected behavior

Data passed from add-n to HA.

## Actual behavior

NO data in HA from ZWave devices anymore.

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by Masterz69** [comment]
HA not show possible upgrades:
![image](https://user-images.githubusercontent.com/15225823/171583075-d5f477c3-6ac8-4e51-acde-4c49f8892a3c.png)

**Comment by frenck** [comment]
From the release notes...

![CleanShot 2022-06-02 at 09 59 49](https://user-images.githubusercontent.com/195327/171583003-380846be-b7f6-4ddf-a96d-8dc6fa31baaf.png)

<https://www.home-assistant.io/blog/2022/06/01/release-20226/#breaking-changes>

According to your issue report: 

> ZWave JS 2MQTT version 0.39.0

Please upgrade your add-on.

**Comment by Masterz69** [comment]
Unfortunately I do not know how to upgrade in that case, when HA Core is not aware about new version.

**Comment by frenck** [comment]
There is: <https://github.com/hassio-addons/addon-zwavejs2mqtt/releases>

Make sure you have the community repository installed, you can make sure by using this My Home Assistant button (which is also in the documentation of the add-on).

[![Open your Home Assistant instance and show the add add-on repository dialog with a specific repository URL pre-filled.](https://my.home-assistant.io/badges/supervisor_add_addon_repository.svg)](https://my.home-assistant.io/redirect/supervisor_add_addon_repository/?repository_url=https%3A%2F%2Fgithub.com%2Fhassio-addons%2Frepository)

**Comment by Masterz69** [comment]
Looks some repositories suddenly disappeared from list. Using add-on more than year, so it was in list before 2022.6.0.

Now tried to add, but supervisor fails:
```
22-06-02 11:07:37 INFO (MainThread) [supervisor.store.git] Cloning add-on https://github.com/hassio-addons/addon-zwavejs2mqtt/releases repository
22-06-02 11:07:40 ERROR (MainThread) [supervisor.store.git] Can't clone https://github.com/hassio-addons/addon-zwavejs2mqtt/releases repository: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v --recursive --depth=1 --shallow-submodules https://github.com/hassio-addons/addon-zwavejs2mqtt/releases /data/addons/git/5d294422
  stderr: 'Cloning into '/data/addons/git/5d294422'...
remote: Not Found
fatal: repository 'https://github.com/hassio-addons/addon-zwavejs2mqtt/releases/' not found
'.
```

Then tries this magic button - looks it works, Add-on update appears.

Thank You  very much.
