### ISSUE TITLE
[Feature] Z-Wave Network Graph as Camera Entity

### ISSUE THREAD

**Issue by GitHubGoody** [hassio-addons/addon-zwavejs2mqtt#381]
Is it possible to create a camera entity for the Z-Wave Network Graph?

**Comment by frenck** [comment]
Add-ons do not provide and/or create entities. This is a feature request that cannot be done from this project.

**Comment by GitHubGoody** [comment]
@frenck OK...wouldn't the add-on have to pass the image from zwavejs2mqtt to the Z-Wave JS integration?

If anyone stumbles across this later and would like to vote, here's where I put the feature request for the Z-Wave JS integration:
https://community.home-assistant.io/t/z-wave-js-network-graph-as-camera-entity/427256

**Comment by frenck** [comment]
> OK...wouldn't the add-on have to pass the image from zwavejs2mqtt to the Z-Wave JS integration?

Not the add-on. Add-ons wrap existing applications, in this case: zwavejs2mqtt. The add-on itself is the runtime for that application.

That said, Home Assistant communicates with the add-on via the Z-Wave JS Server that is built-in into the zwavejs2mqtt application, which communicates directly with the Z-Wave JS layer underneath it (just like zwavejs2mqtt does).

So, effectively, it's not zwavejs2mqtt talking with Home Assistant, but the layers below it. zwavejs2mqtt provides an interface for Z-Wave JS, but does not communicate with HA.
