### ISSUE TITLE
Running but wont connect

### ISSUE THREAD

**Issue by AdamsLab01** [hassio-addons/addon-zwavejs2mqtt#393]
# Problem/Motivation

Z-Wave JS to MQTT is running but when opening the webui I get a "502 bad gateway." Z-Wave JS reports "Retrying setup: Failed to connect:"

## Expected behavior

I expected it to work

## Actual behavior

It's not working, see above.

## Steps to reproduce

Don't know, this happed after the last update. I finally looked at it and found that Z-Wave JS to MQTT was not running. I started it and the above described issue is what I'm getting now.

## Proposed changes

Fix the issue that's resulting in Z-Wave JS to MQTT not working :)

FYI, I tried (several times) to restart Home Assistant and saw this in the logs:

Could not fetch stats for a0d7b954_zwavejs2mqtt: Container addon_a0d7b954_zwavejs2mqtt is not running

But when I checked the zwavejs2mqtt addon page it was running.

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: Z-Wave JS to MQTT
 Fully configurable Z-Wave JS to MQTT gateway and control panel; based on Zwavejs2Mqtt
-----------------------------------------------------------
 Add-on version: 0.44.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 8.2  (aarch64 / odroid-n2)
 Home Assistant Core: 2022.7.5
 Home Assistant Supervisor: 2022.07.0

Oh, just saw this in the js2Mqtt log:

2022-07-16 10:12:44.886 WARN STORE: scenes.json not found
2022-07-16 10:12:44.905 INFO APP: HTTPS is enabled. Loading cert and keys
2022-07-16 10:12:44.909 INFO APP: Cert and key not found in store, generating fresh new ones...
Error: Could not find openssl on your system on this path: openssl
    at /opt/node_modules/pem/lib/openssl.js:237:23
[10:12:44] WARNING: zwavejs2mqtt crashed, halting add-on
s6-rc: info: service legacy-services: stopping
[10:12:44] INFO: zwavejs2mqtt stoped, restarting...
[10:12:45] INFO: NGinx stoped, restarting...
s6-svwait: fatal: supervisor died
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

So it's crashing because it can't find openssl...? Interesting that it's crashed but the GUI is showing that it's still running.

**Comment by frenck** [comment]
it isn't running... if the UI shows that, that would be a different bug, but the logs clearly show a shutdown.

**Comment by AdamsLab01** [comment]
> it isn't running... if the UI shows that, that would be a different bug, but the logs clearly show a shutdown.

Right, I think it's starting, crashing, and restarting but the UI isn't responding fast enough to show that it's not running. I'm not saying that's part of the issue... Just an observation. 

Any idea of the cause/fix?

**Comment by frenck** [comment]
It is interesting, as this add-on does not use SSL (as the interface is provided via Ingress internally).

So I have no idea what may have caused this?

**Comment by AdamsLab01** [comment]
So I'm just SOL?

**Comment by AdamsLab01** [comment]
I mean... It's your addon that's calling for openssl and can't find it...

 ______                       _     ___                  _   _   
|___  /                      (_)   |__ \                | | | |  
   / /_      ____ ___   _____ _ ___   ) |_ __ ___   __ _| |_| |_ 
  / /\ \ /\ / / _` \ \ / / _ \ / __| / /| '_ ` _ \ / _` | __| __|
 / /__\ V  V / (_| |\ V /  __/ \__ \/ /_| | | | | | (_| | |_| |_ 
/_____|\_/\_/ \__,_| \_/ \___| |___/____|_| |_| |_|\__, |\__|\__|
                            _/ |                      | |        
                           |__/                       |_|        
2022-07-18 09:16:00.129 WARN STORE: scenes.json not found
2022-07-18 09:16:00.147 INFO APP: HTTPS is enabled. Loading cert and keys
2022-07-18 09:16:00.150 INFO APP: Cert and key not found in store, generating fresh new ones...
Error: Could not find openssl on your system on this path: openssl
    at /opt/node_modules/pem/lib/openssl.js:237:23
[09:16:00] WARNING: zwavejs2mqtt crashed, halting add-on
s6-rc: info: service legacy-services: stopping
[09:16:00] INFO: zwavejs2mqtt stoped, restarting...
[09:16:00] INFO: NGinx stoped, restarting...
[09:16:00] INFO: zwavejs2mqtt stoped, restarting...
s6-svwait: fatal: supervisor died
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by AdamsLab01** [comment]
Are we just in a place where you're not going to offer any help on this issue?

**Comment by AdamsLab01** [comment]
Well, looks like this addon is completely borked. I removed Z-Wave JS to MQTT and Z-Wave JS and tried reinstalling and got: "Failed to get Z-Wave JS add-on info."

So yeah, based on all the evidence: failed addon(s), developer being unresponsive to issues, and now this, I'd say this thing is dead. Hopefully there will be something to replace this soon.

**Comment by TheDK** [comment]
You a) do not seem the have clue who „the developer“ is and b) really think, that if an add-on used probably by thousands of people is completely broken your the only one to notice?

@frenck told you that he has no idea what caused your problem. It’s specific to your install. So yes, you are SOL and need to troubleshoot your install as no one can do that for you.

**Comment by frenck** [comment]
> Are we just in a place where you're not going to offer any help on this issue?

Based on the data given and provided I have no idea what to look for, nor do I have an idea how to get more information regarding this.

It's an open-source project, feel free to contribute if you can fix it. I'm happy to add a solution for it.

**Comment by frenck** [comment]
> So yeah, based on all the evidence: failed addon(s), developer being unresponsive to issues, and now this, I'd say this thing is dead. Hopefully there will be something to replace this soon.

LOL. Ok, in that case, we can consider this issue solved for now 🤷 

Let me be really clear on this; I have no obligation to help you or to provide support. This add-on is provided for free AS IS (see also license). I'm happy to help where I can, but I don't have a magic wand or crystal ball. If you like to have the entitlement to require support, please get yourself a commercial product that provides you just that.

(no hard feeling otherwise btw)

../Frenck

**Comment by AdamsLab01** [comment]
> You a) do not seem the have clue who „the developer“ is and b) really think, that if an add-on used probably by thousands of people is completely broken your the only one to notice?
> 
> @frenck told you that he has no idea what caused your problem. It’s specific to your install. So yes, you are SOL and need to troubleshoot your install as no one can do that for you.

Yeah, I can't even reinstall the thing so... Nothing, literally noting ahs changed expect for the last update to Z-Wave JS... And it's the damn addon that's calling for something that's not there so... 

Anyway thanks for the stellar help.

> > So yeah, based on all the evidence: failed addon(s), developer being unresponsive to issues, and now this, I'd say this thing is dead. Hopefully there will be something to replace this soon.
> 
> LOL. Ok, in that case, we can consider this issue solved for now 🤷
> 
> Let me be really clear on this; I have no obligation to help you or to provide support. This add-on is provided for free AS IS (see also license). I'm happy to help where I can, but I don't have a magic wand or crystal ball. If you like to have the entitlement to require support, please get yourself a commercial product that provides you just that.
> 
> (no hard feeling otherwise btw)
> 
> ../Frenck

After an update to the addon you develop (only thing that's changed) it's calling for something (openssl) that isn't there and you won't even bother to offer an explanation as to why...

**Comment by frenck** [comment]
I am sorry you have troubles, but the fact is, your are the only one reporting a startup issue (out of 15000 instances running the 0.44.0 version).

It is not something common. Again, I don't have a crystal ball or magic wand.
