### ISSUE TITLE
installation docs not quite correct?

### ISSUE THREAD

**Issue by strelniece** [hassio-addons/addon-zwavejs2mqtt#406]
When following the part of the installation docs, "Now it is time to set up Home Assistant:" it didn't mach the actual way I had to do it.

To start with I had two Autodiscovered integrations, the first came right after onboardning, the second after installing the addon.

Both of them wanted to install the integration without the option to uncheck the box.

When I instead chose "other z-wave", I got a dialog where I could add the server.

Now the option is gone, so I can't write down exactly what I did without starting all over I guess...

**Comment by frenck** [comment]
Tested the steps and concluded the existing documentation matches the latest version of Home Assistant (2022.10 development).

../Frenck
