### ISSUE TITLE
0.46.0 update breaks Ecolink DWZWAVE25 interview

### ISSUE THREAD

**Issue by ee-partners** [hassio-addons/addon-zwavejs2mqtt#409]
# Problem/Motivation

I have 5 Ecolink DWZWAVE25 sensors and successfully added the first three with v0.45.0 installed. For each of those there is a Door State entity (which was enabled after adding the device) and 6 hidden/disabled entities listed in the ‘Sensors’ section of the device screen in ZwaveJS. Tried to add the two remaining devices after upgrading to v0.46.0, and only the 6 hidden/disabled entities get added in sensors. The Door State entity never appears. 

Fresh install of HA OS on a Pi3B. Using the ZWaveJS2mqtt addon. Aeotec Z-stick 7. Also have the ZwaveJS integration installed. DriverVersion: 10.0.3, ServerVersion: 1.22.1

## Expected behavior

Door State entity should appear and be automatically configured, as in v0.45.0. 

If I do a diff on the device diagnostics between the working and non-working devices, I see that the following expected entity is missing:
```
{
        "domain": "binary_sensor",
        "entity_id": "binary_sensor.z_wave_door_window_sensor_access_control_window_door_is_open",
        "original_name": "Z-Wave Door/Window Sensor: Access Control - Window/door is open",
        "original_device_class": "door",
        "disabled": false,
        "disabled_by": null,
        "hidden_by": null,
        "original_icon": null,
        "entity_category": null,
        "supported_features": 0,
        "unit_of_measurement": null,
        "primary_value": {
          "command_class": 113,
          "command_class_name": "Notification",
          "endpoint": 0,
          "property": "Access Control",
          "property_name": "Access Control",
          "property_key": "Door state",
          "property_key_name": "Door state",
          "state_key": 22
        }
      },
```

An endpoint is also missing one of the state descriptors:
```
{
          "endpoint": 0,
          "commandClass": 113,
          "commandClassName": "Notification",
          "property": "Access Control",
          "propertyKey": "Door state",
          "propertyName": "Access Control",
          "propertyKeyName": "Door state",
          "ccVersion": 5,
          "metadata": {
            "type": "number",
            "readable": true,
            "writeable": false,
            "label": "Door state",
            "ccSpecific": {
              "notificationType": 6
            },
            "min": 0,
            "max": 255,
            "states": {
              "23": "Window/door is closed"
            }
          }
        },
```
There ought to be another entry in states ("22": "Window/door is open",)

## Actual behavior

Door Entity is missing.

## Steps to reproduce

Add new device or re-interview using v0.46.0.

## Proposed changes

Only thing that has worked so far is rolling back to v0.45.0. Nothing I did while using v0.46.0 helped, including excluding and re-adding the device, or reinterviewing. Looking at the logs, it does seem that the state was being reported by the device correctly during transitions, and all the devices that were added in v0.45.0 continued to work as expected, so my suspicion is that the issue is just with the setup process.

**Comment by doug-hoffman** [comment]
I'm seeing the same exact thing with the Sensative 11-01-011 door sensors. I was also missing sensors on Schlage BE469ZP locks. I spent several hours excluding/including and re-interviewing the broken nodes, but the missing entities would never appear. I haven't re-interviewed any other devices on 0.46.0, so this isn't an exhaustive list.

Downgrading to 0.45.0 and re-interviewing the nodes resolved both problems.

What we're seeing after upgrading to 0.46.0 seems to be the result of the bump to zwavejs2mqtt 7.0.0, which includes zwave-js v10 support. There is an issue tracking things that break with the new v10 driver: zwave-js/node-zwave-js#4994. This issue was also mentioned in PR #407 that bumped zwavejs2mqtt to 7.0.0, so devs on both sides are aware that things are breaking.

With HA 2022.9 about to drop and requiring the newer API version, people are going to have no choice but to run 0.46.0 soon and this will become a much more urgent problem.

**Comment by doug-hoffman** [comment]
I submitted PR #411 to bump zwavejs2mqtt to v7.1.0, which bumps node-zwave-js from v10.0.2 to v10.0.4. Seems to include some possibly helpful bugfixes. 🤞

https://github.com/zwave-js/node-zwave-js/releases/tag/v10.0.3
https://github.com/zwave-js/node-zwave-js/releases/tag/v10.0.4

**Comment by only1kairi** [comment]
I am having the same issue. My new Ecolink DWZWAVE25 door switches are not connecting correctly, non of the sensors are working for that device. I saw a long error in the logs.

**Comment by anderson-pa** [comment]
> I am having the same issue. My new Ecolink DWZWAVE25 door switches are not connecting correctly, non of the sensors are working for that device. I saw a long error in the logs.

Can you confirm if you are on v0.46.0 or the new v0.46.1 that released yesterday (including doug-hoffman's PR, I believe). Would be good to know if that update helped resolve the issue or if it persists.

_(Also sorry for potential confusion, but I'm the original poster. Just accidentally logged into work account when I submitted the issue)_

**Comment by only1kairi** [comment]
I saw the same issue occurring, my backups didn't include 0.45 which I believe is the version that works. I've attached my screenshot to show the issue. all of the sensors are not found but the device was registered.
![Capture-today](https://user-images.githubusercontent.com/38743914/189142724-f1b3c96a-752d-41d4-b0fd-7e502bbd6386.PNG)

**Comment by doug-hoffman** [comment]
The issue with DWZWAVE25 and other door/window sensors is fixed in zwave-js/node-zwave-js#5037 (in release 10.1.0). They haven't rolled out a new zwavejs2mqtt release with the fix yet, but I'll keep an eye on it and do another PR, unless someone beats me to it.

**Comment by doug-hoffman** [comment]
The zwavejs2mqtt project has bumped zwave-js to 10.1.0 in zwave-js/zwavejs2mqtt#2643. No new release for us to use yet.

**Comment by gsemet** [comment]
My smart plugs (fibajo) and all devices that returns temperature or power does not returns anything, but switching plugs still works.

**Comment by TheDK** [comment]
The project does not have recent open issues mentioning this, last release was 11 days ago. Are you guys sure there is a general problem or bug?

**Comment by doug-hoffman** [comment]
A new zwavejs2mqtt release is out and frenck has already updated the addon. Door/window sensors are fixed. 🎉

**Comment by frenck** [comment]
Good to know! Will close the issue on this end in that case 👍
