### ISSUE TITLE
Status of Honeywell TH6320ZW Thermostats not displayed in HA following the v0.46.0 update

### ISSUE THREAD

**Issue by cptskippy** [hassio-addons/addon-zwavejs2mqtt#410]
# Problem/Motivation

After recent update to v0.46.0, the three Honeywell TH6320ZW Thermostats I have on my network are no longer reporting status changes or updates back to Home Assistant.  All other Z-Wave devices appear to function correctly and accurately report state.

## Expected behavior

If I manually adjust the thermostat, I expect the new values to be reflected in Home Assistant.  If I make changes through the Home Assistant UI, I expect Home Assistant to reflect those changes.

## Actual behavior

When I make changes (e.g. lower temperature) on the thermostat directly or through the Home Assistant UI, the values will revert back to the prior value in Home Assistant after about 5 seconds.  However the changes are accurately displayed on the thermostat itself and in the Z-Wave JS to MQTT Control Panel when I look a the device values.

## Steps to reproduce

1) Adjustment the temperature of a Honeywell TH6320ZW Thermostat to 82°F either on the device or through Home Assistant.

![Thermostat displaying a temperature of 78°F and a setpoint of 82°F](https://user-images.githubusercontent.com/5817292/188283998-4f3d973b-8289-43b5-91c5-c3fc761987c7.png)

2) Observe that the actual temperature or setpoint values in Home Assistant do not reflect those of the Thermostat.

![Lovelace Control displaying a temperature of 76°F and a setpoint of 76°F](https://user-images.githubusercontent.com/5817292/188284068-d258f888-612e-4bb9-9e52-489a91c7429a.png)

![Devices Settings dialog displaying a temperature of 76°F and a setpoint of 76°F](https://user-images.githubusercontent.com/5817292/188284093-e8890f9c-7299-4b65-a8c1-eb7f33d274c5.png)

3) Observe that the actual values of the Thermostat are reflected in the Z-Wave JS to MQTT Control Panel.

![Z-Wave JS to MQTT Control Panel Device Values panel displaying a temperature of 78°F and a setpoint of 82°F](https://user-images.githubusercontent.com/5817292/188284117-0afa559a-471d-4484-ae4a-4e1d6ffe2603.png)

## Proposed changes

Ensure that Z-Wave JS to MQTT is accurately reporting status changes to Home Assistant.

**Comment by twinkie0101** [comment]
I had the same issue with v0.46.0, restored v0.45.0 and is working as expected.

**Comment by cptskippy** [comment]
@twinkie0101 how did you rollback?

**Comment by twinkie0101** [comment]
@cptskippy - I keep full backups.  If you go to the the system control menu and view backups, you should see a list (assuming you backup up your files).  Click on the name of the backup and you should have a partial backup option, click that and select the Z-Wave JS to MQTT under add-ons (it will tell you what version), then click restore.  

![image](https://user-images.githubusercontent.com/79336898/188732612-f1ee5002-11ba-486f-8c39-bab90bf46b64.png)

**Comment by twinkie0101** [comment]
This issue persists with the most recent update v0.46.1 as well.  Do not recommend updating if you have the Honeywell HVAC controls.

**Comment by cptskippy** [comment]
@twinkie0101 I confirmed that v0.46+ work with Core v2022.9 but not with v2022.8.

**Comment by TheDK** [comment]
@frenck There was a new release of this today which includes the bump of zwave-js@10.1.0 (which itself was released 9 days ago). If it's not too much effort it would be great if you could bump it here as well so we can test if general issues persist and report back here: https://github.com/zwave-js/node-zwave-js/issues/4994#issuecomment-1250799540
Thanks!

**Comment by frenck** [comment]
@TheDK Already done

![CleanShot 2022-09-19 at 11 52 02](https://user-images.githubusercontent.com/195327/190992692-5930f2a4-0b42-40f7-8166-ce74a0abaf06.png)

**Comment by TheDK** [comment]
@frenck perfect, thanks!

**Comment by TheDK** [comment]
Update: For me everything is working normal with this update.

**Comment by frenck** [comment]
Alright closing this issue in that case.
