### ISSUE TITLE
mcohome fan coil broke after latest update

### ISSUE THREAD

**Issue by kostas2911** [hassio-addons/addon-zwavejs2mqtt#44]
mcohome fancoil climate entity is unavailable after latest update.
Although temprature sensor is running

**Comment by frenck** [comment]
Add-on wrap existing applications. We do not develop the application running in the add-on itself. Please report your issue upstream. Thanks!

**Comment by kostas2911** [comment]
thanks but addon is fine with Z-Wave JS
