### ISSUE TITLE
climate.thermostat entity unavailable after update 0.4.1 to 0.4.2

### ISSUE THREAD

**Issue by JAAlperin** [hassio-addons/addon-zwavejs2mqtt#47]
# Problem/Motivation

Lost control of Nortek Security & Control LLC Z-Wave Plus Thermostat GoControl GC-TBZ48 Thermostat

## Expected behavior

> climate.thermostat entity was available and functioning with 0.4.1.

> climate.thermostat entity Became unavailable with 0.4.2

## Steps to reproduce

> update to zwavejs2mqtt 0.4.2 (climate entity disappears).  Selective restore 0.4.1 from snapshot (climate entity OK).  Note: other entities of thermostat are unaffected.  Only the climate integration seems impacted.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Add-ons wrap existing applications, we don't build zwavejs2mqtt. Please report your issue upstream. Once it is fixed, the add-on will update as well.

Thanks 👍

**Comment by JAAlperin** [comment]
Thank you, Frenk

Regards,

Jeff Alperin

H: 561-666-7789
C: 561-797-9876

**Comment by JAAlperin** [comment]
Issue #648 opened in zwave-js/zwavejs2mqtt
