### ISSUE TITLE
Battery values in home assistant show as 100.0%

### ISSUE THREAD

**Issue by blair287** [hassio-addons/addon-zwavejs2mqtt#52]
# Problem/Motivation

> (Why the issue was filed)

Battery sensors show in HA as 100.0% seems a little excessive just 100% etc would be sufficient and keep with other battery values shown in HA

## Expected behavior

> (What you expected to happen)

dont need the one decimal point of battery

## Actual behavior

> (What actually happened)

always showing battery with a decimal point 

## Steps to reproduce

> (How can someone else make/see it happen)

just add supervisior addon and pair device with battery then add to HA with official integration

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

Remove the .0 on battery values HA on every other integration only shows battery values to the nearest 1 not .0
![zwave battery](https://user-images.githubusercontent.com/44187409/108601653-914d0f80-7395-11eb-844f-7cf6335396b6.JPG)

**Comment by frenck** [comment]
If you want to report a bug with the Home Assistant integration, please report the bug with Home Assistant. This is the community add-on, which has nothing to do with the integration.

Thanks 👍
