### ISSUE TITLE
Upgrade to Release 1.4.0

### ISSUE THREAD

**Issue by bepsoccer** [hassio-addons/addon-zwavejs2mqtt#56]
# Problem/Motivation

Is it appropriate to request we bump the version of the underlying project?  I'm unsure of the best way to make this inquiry, I didn't want to simply submit a pull request.  If there's some other processes working on this, just ignore me.

## Proposed changes

Bump the dockerfile to use the latest zwavejs2mqtt v1.4.0 release.

**Comment by frenck** [comment]
We track issue, not requests in GitHub. Thanks for understanding.
