### ISSUE TITLE
ZWave JS server version incompatible with HA integration

### ISSUE THREAD

**Issue by Icexist** [hassio-addons/addon-zwavejs2mqtt#58]
# Problem/Motivation

ZWave JS Integration doesn't start correctly

## Expected behavior

ZWave JS to load.

## Actual behavior

Log error:

```
Logger: homeassistant.components.zwave_js
Source: components/zwave_js/__init__.py:208
Integration: Z-Wave JS (documentation, issues)
First occurred: 6:11:19 PM (12 occurrences)
Last logged: 6:22:35 PM

Failed to connect: Z-Wave JS Server needs to be at least version 1.0.0. Found 1.0.0-beta.8
Failed to connect: Cannot connect to host a0d7b954-zwavejs2mqtt:3000 ssl:default [Connect call failed ('172.30.33.1', 3000)]
```

## Steps to reproduce

Try to load zwave_js with this addon in core-2021.3.0b0.

## Proposed changes

Upgrade server to 1.0.0

I suspect that this is an issue with the core zwave_js integration, and I've [filed a report](https://github.com/home-assistant/core/issues/47029), but I wanted to put an issue here as an FYI.

**Comment by frenck** [comment]
As far as I understand, upgrading now will break it for users on the current stable version of Home Assistant. So, I cannot upgrade...

**Comment by Icexist** [comment]
Rock, hard place and all that. Well, I got myself into this situation by upgrading this addon (without a backup ... facepalm) and losing the climate entity in 2012.2.1, then upgrading to the beta to try and get it back. I'll patiently play the waiting game!

**Comment by marcelveldt** [comment]
We have a solution for this in the working...

**Comment by johntdyer** [comment]
I thnk this is the fix https://github.com/home-assistant-libs/zwave-js-server-python/pull/145

**Comment by marcelveldt** [comment]
@johntdyer That is incorrect.
This would be the fix that allows us to have version independency between HA versions and add-on/server versions:
https://github.com/home-assistant-libs/zwave-js-server-python/pull/144

**Comment by stboch** [comment]
@frenck would it be possible to release an update under the BETA addon repo as this shouldn't affect users who are set to auto-update? its not clean but it would allow some of us to continue to test the new beta with zwavejs2mqtt

**Comment by marcelveldt** [comment]
A fix is on it's way, just a little bit of patience please.

**Comment by thundergreen** [comment]
will it be in beta or stable addon version ? Facing same issue. I am patient as i see it has been recognised and a fix is on its way :) Thanks fellows u r Wonderful :)

**Comment by thundergreen** [comment]
Just saw zwave2mqtt has an update: https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v2.0.0 can we please update this addon asap ?

**Comment by frenck** [comment]
@thundergreen I'm aware. I generally skip the task and do something else first if people start pushing in asking for updates.

**Comment by thundergreen** [comment]
@frenck  please don't take it as pushing you.not my intention at all.i really highly appreciate all the hard work you do and was just scared this could slip between your attention that's all 😃  I know your endless efforts in home assistant and I think I speak for everybody here. I'll then let you alone by knowing this issue is present for you . Have a pleasant day

**Comment by frenck** [comment]
Add-on version 0.5.0 is released.

**Comment by thundergreen** [comment]
Fixed! :) Great thanks :)
