### ISSUE TITLE
Dead device still "Available" is Entities list

### ISSUE THREAD

**Issue by Masterz69** [hassio-addons/addon-zwavejs2mqtt#63]
# Problem/Motivation

Abnormal status for unavailable/dead Z-Wave device.

## Expected behavior

Z-Wave Dead devices MUST become with Status = Unavailable in HA and still visible in dashboards etc., just grayed.

## Actual behavior

Dead device disappear from dashboards, despite still Available in Entities list.

## Steps to reproduce

Just disconnect power from Z-Wave device and wait.

## Proposed changes

While powered:
![ZW_Dead_01](https://user-images.githubusercontent.com/15225823/109414825-c1139d00-79bd-11eb-9c76-94f7c1f4eb85.png)
![ZW_Dead_02](https://user-images.githubusercontent.com/15225823/109414826-c40e8d80-79bd-11eb-9daf-418892406d78.png)
![ZW_Dead_03](https://user-images.githubusercontent.com/15225823/109414827-c7a21480-79bd-11eb-9760-8115ec016cd9.png)

Device powered off:
![ZW_Dead_04](https://user-images.githubusercontent.com/15225823/109414830-d1c41300-79bd-11eb-8ec9-2aa4681c9934.png)
Entity status is NOT unavailable - see column status:
![ZW_Dead_05](https://user-images.githubusercontent.com/15225823/109414841-e6081000-79bd-11eb-8312-51a98d056c6f.png)

Thats how it mast be: status = Unavailable, no message in entity card.
![ZW_Dead_06](https://user-images.githubusercontent.com/15225823/109414849-f324ff00-79bd-11eb-850c-d14f943f465f.png)

**Comment by Masterz69** [comment]
After HA host (whole host) reboot - it behave differently.
Entities have status Restore abd visible in Dashobards.

Grayed, as expected.
![Zwave_Dead_07](https://user-images.githubusercontent.com/15225823/109415234-38e2c700-79c0-11eb-9e1b-681e3c865b06.png)

Entity status:
![Zwave_Dead_08](https://user-images.githubusercontent.com/15225823/109415246-44ce8900-79c0-11eb-8fd5-050e3b1a657d.png)

After powering device - all fine.

Will power off once more time and report.

**Comment by Masterz69** [comment]
So, powered off device - after all HA host reboot.

Now IMHO Z-Wave control panel works fine/well - device details still in place:
![ZW_Dead_09](https://user-images.githubusercontent.com/15225823/109416315-0b991780-79c6-11eb-9f6a-f7092d3b2f34.png)

But ... entities status in list is NOT Unavailable, despite device is DEAD.
![ZW_Dead_11](https://user-images.githubusercontent.com/15225823/109416327-1fdd1480-79c6-11eb-9627-8634f33c75d2.png)

**Comment by Masterz69** [comment]
Sending a command to turn on towards Dead device (as entitis is availabe in dashboard), causes:
* error in Core log;
* freeze (couple of seconds) to execute commands, send to other Z-Wave devices.

2021-02-28 13:09:54 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547980276064] Command failed: unknown_error
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 136, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1455, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1490, in _execute_service
await handler.job.target(service_call)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
await self.hass.helpers.service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 595, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 632, in _handle_entity_call
await result
File "/usr/src/homeassistant/homeassistant/components/zwave_js/switch.py", line 58, in async_turn_on
await self.info.node.async_set_value(target_value, True)
File "/usr/local/lib/python3.8/site-packages/zwave_js_server/model/node.py", line 250, in async_set_value
result = await self.client.async_send_command(
File "/usr/local/lib/python3.8/site-packages/zwave_js_server/client.py", line 64, in async_send_command
return await future
zwave_js_server.exceptions.FailedCommand: Command failed: unknown_error

**Comment by frenck** [comment]
So you have 2 issues on your hand here for which, unfortunately, none of those are something the add-on can fix.

> Z-Wave Dead devices MUST become with Status = Unavailable in HA and still visible in dashboards etc., just grayed.

and

> Sending a command to turn on towards Dead device (as entitis is availabe in dashboard), cause

Both cases, please report as (separate) issues with the Home Assistant project: 

<https://github.com/home-assistant/core/issues>

Thanks! 👍
