### ISSUE TITLE
Fibaro Smoke Sensor

### ISSUE THREAD

**Issue by lelimit** [hassio-addons/addon-zwavejs2mqtt#66]
# Problem/Motivation
Fibaro Smoke Sensor not recognised after inclusion. Node is added but no information can be obtained. 

> (Why the issue was filed)
Not able to use Fibaro smoke sensor. Have tried both normal inclusion and secure inclusion. 

## Expected behavior
Node recognized as Fibaro smoke sensor. 

> (What you expected to happen)
Retrieve information of node

## Actual behavior
Node added. No device info, manufacturer info and so on 

> (What actually happened)
Only Status is resolved. Status = asleep

## Steps to reproduce
Open Control Panel. 
Click on Add/Remove Device 
Choose Secure Inclusion
Triple click on Fibaro Smoke Sensor
Node added but no info from device

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
There is not much I can do from an add-on perspective, as an add-on wraps existing applications.
Please report your issue upstream. Thanks 👍
