### ISSUE TITLE
How to trigger the sound of Aeotec Doorbell 6 (ZW164)

### ISSUE THREAD

**Issue by seoulop** [hassio-addons/addon-zwavejs2mqtt#72]
# Problem/Motivation

> I'm using Aeotec Doorbell 6 (ZW164) and couldn't trigger the sound from Home assistant.

## Expected behavior

> I found an issue about ZW164 on Zwave2mqtt, ( https://github.com/cgarwood/homeassistant-zwave_mqtt/issues/45 )
  and it looks possible to make the sound by publishing a mqtt command.

## Actual behavior

> But mqtt topics of zwavejs2mqtt is little bit different with zwave2mqtt.

![image](https://user-images.githubusercontent.com/46134706/109969465-83e53d00-7d26-11eb-99b6-9018cd39ec4a.png)

'homeassistant/nodeID_9/121/2/toneId' is the topic shows change when the doorbell make the sound by tampering.
and following is the value.
{
    "id": "9-121-2-toneId",
    "nodeId": 9,
    "commandClass": 121,
    "commandClassName": "Sound Switch",
    "endpoint": 2,
    "property": "toneId",
    "propertyName": "toneId",
    "type": "number",
    "readable": true,
    "writeable": true,
    "label": "Play Tone",
    "stateless": false,
    "min": 0,
    "max": 30,
    "list": true,
    "states": [
        {
            "text": "off",
            "value": 0
        },
        {
            "text": "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000 (5 sec)",
            "value": 1
        },
        {
            "text": "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000 (9 sec)",
            "value": 2
        },
        {
            "text": "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000 (11 sec)",
            "value": 3
        },
        {
            "text": "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000 (2 sec)",
            "value": 4
        },
        {
            "text": "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000 (13 sec)",
            "value": 5
        },
        {
            "text": "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000 (7 sec)",
            "value": 6
        },
        {
            "text": "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000 (31 sec)",
            "value": 7
        },
        {
            "text": "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000 (6 sec)",
            "value": 8
        },
        {
            "text": "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000 (11 sec)",
            "value": 9
        },
        {
            "text": "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000 (6 sec)",
            "value": 10
        },
        {
            "text": "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000 (35 sec)",
            "value": 11
        },
        {
            "text": "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000 (5 sec)",
            "value": 12
        },
        {
            "text": "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000 (38 sec)",
            "value": 13
        },
        {
            "text": "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000 (41 sec)",
            "value": 14
        },
        {
            "text": "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000 (37 sec)",
            "value": 15
        },
        {
            "text": "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000 (46 sec)",
            "value": 16
        },
        {
            "text": "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000 (35 sec)",
            "value": 17
        },
        {
            "text": "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000 (62 sec)",
            "value": 18
        },
        {
            "text": "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000 (15 sec)",
            "value": 19
        },
        {
            "text": "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000 (7 sec)",
            "value": 20
        },
        {
            "text": "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000 (8 sec)",
            "value": 21
        },
        {
            "text": "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000 (64 sec)",
            "value": 22
        },
        {
            "text": "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000 (4 sec)",
            "value": 23
        },
        {
            "text": "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000 (10 sec)",
            "value": 24
        },
        {
            "text": "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000 (4 sec)",
            "value": 25
        },
        {
            "text": "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000 (12 sec)",
            "value": 26
        },
        {
            "text": "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000 (1 sec)",
            "value": 27
        },
        {
            "text": "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000 (5 sec)",
            "value": 28
        },
        {
            "text": "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000 (2 sec)",
            "value": 29
        },
        {
            "text": "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000 (27 sec)",
            "value": 30
        },
        {
            "text": "default",
            "value": 255
        }
    ],
    "value": 0,
    "lastUpdate": 1614861583195,
    "nodeName": "",
    "nodeLocation": ""
}

I have completely no idea I have to publish what command to which topic to trigger the sound.

And I can trigger the sound from Zwavejs control panel below, but don't know how to use it in the automation.
![image](https://user-images.githubusercontent.com/46134706/109971858-4209c600-7d29-11eb-8497-60f246128d1c.png)

Any advice would be appreciated

## Proposed changes

I hope there are an entity to trigger the sound.

**Comment by frenck** [comment]
The linked issue is about openzwave, not zwave JS. So anything there doesn't apply.

About your question, I have no idea. This might not be the right place to pick this up.

**Comment by seoulop** [comment]
> The linked issue is about openzwave, not zwave JS. So anything there doesn't apply.
> 
> About your question, I have no idea. This might not be the right place to pick this up.

Thank you for the comment.

Yes, I had to search HA community for this issue first.
And it seems like the siren support is on the roadmap for the zwavejs integration.

Sorry for the bothering you :)
