### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by gerdesj** [hassio-addons/addon-zwavejs2mqtt#75]
I have two HA systems with a certain USB dongle in them.  They both use this path:

`by_id: /dev/serial/by-id/usb-0658_0200-if00`

Note the final - (dash) is not an _ (underscore).  In the addon notes for zwavejs2mqtt, in Setting up the Home Assistant Z-Wave JS integration, 3. Enter ... , Serial Port (eg ...) the path is given as: 

`/dev/serial/by-id/usb-0658_0200_if00`

In the unlikely *cough* event that someone simply copy and pastes the above they will get an error.  It took me a while to spot why 8)

**Comment by frenck** [comment]
system depended. There is no right answer.
