### ISSUE TITLE
Missing the option to see removed devices

### ISSUE THREAD

**Issue by Keldandorin** [hassio-addons/addon-zwavejs2mqtt#77]
# Problem/Motivation

Missing the option to see removed devices after last update(could be the one before sins I did a 2 version update)

## Expected behavior

to be able to filter them

## Actual behavior

Missing option

## Proposed changes

make it possible to see removed devices and off course be able to reenable them by replacing node

**Comment by frenck** [comment]
Hi there!

Thanks for opening up an issue, however, you are asking for implementing features into Z-Wave JS to MQTT itself; not the add-on.

Add-ons wrap existing applications, we don't develop the application running inside the add-on. Please, report feature requests upstream, in this case with Z-Wave JS to MQTT. If it gets implemented, the add-on will automatically get it as well.


Thanks 👍
