### ISSUE TITLE
scenes.json & git not found

### ISSUE THREAD

**Issue by Veldkornet** [hassio-addons/addon-zwavejs2mqtt#8]
# Problem/Motivation
During the boot of the container, I notice that scenes.json and git are not found.
There was also a second json not found, but it seems to have created this somewhere along the road... Unclear if that’s the intention for scenes.json as well.
```
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] configuration.sh: executing... 
[cont-init.d] configuration.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[11:24:05] INFO: Starting the Z-Wave JS to MQTT...
 ______                       _     ___                  _   _   
|___  /                      (_)   |__ \                | | | |  
   / /_      ____ ___   _____ _ ___   ) |_ __ ___   __ _| |_| |_ 
  / /\ \ /\ / / _` \ \ / / _ \ / __| / /| '_ ` _ \ / _` | __| __|
 / /__\ V  V / (_| |\ V /  __/ \__ \/ /_| | | | | | (_| | |_| |_ 
/_____|\_/\_/ \__,_| \_/ \___| |___/____|_| |_| |_|\__, |\__|\__|
                            _/ |                      | |        
                           |__/                       |_|        
2021-01-31 11:24:07.098 WARN STORE: scenes.json not found
/bin/sh: git: not found
2021-01-31 11:24:13.760 INFO APP: Version: 1.0.1
2021-01-31 11:24:13.763 INFO APP: Application path:/opt
2021-01-31 11:24:13.955 INFO MQTT: MQTT is disabled
2021-01-31 11:24:13.993 INFO ZWAVE: Connecting to /dev/serial/by-id/usb-xxxx_xxxx-if00
2021-01-31 11:24:14.074 INFO APP: Listening on port 44920
[11:24:14] INFO: Starting NGinx...
2021-01-31 11:24:14.196 INFO ZWAVE-SERVER: ZwaveJS server listening on port 3000
```

## Expected behavior
Boots with no problems

## Actual behavior
`2021-01-31 11:24:07.098 WARN STORE: scenes.json not found
/bin/sh: git: not found `

## Steps to reproduce
Install the add-on, start the add-on

## Proposed changes
?

**Comment by Veldkornet** [comment]
Creating a scene and deleting it creates the scenes.json file and then it's happy. Probably not an issue that it's not initially there.

However, I still the the following:
`/bin/sh: git: not found`

**Comment by frenck** [comment]
`/bin/sh: git: not found` Yeah that one is a bit a choice of evils. With `git` available the add-on becomes bigger and will still give a error/warning message 😉 
So I went for the error that took less disk space 😉

**Comment by Veldkornet** [comment]
Oh okay, well if it's expected then I guess we'll just leave it at that 😄

**Comment by frenck** [comment]
I'll leave the issue around for a bit, as I would love to get rid of it (if you don't mind 😉 )

**Comment by sinclairpaul** [comment]
Could we create a dummy file just to swallow the error?, I know its not ideal.

We did something similar in NUT previously https://github.com/hassio-addons/addon-nut/blob/main/nut/rootfs/usr/bin/wall
