### ISSUE TITLE
User codes Two columns layout

### ISSUE THREAD

**Issue by Vartkat** [hassio-addons/addon-zwavejs2mqtt#90]
# Problem/Motivation

more readable interface

## Expected behavior

Two colums layout in User Code panel

## Actual behavior

Three columns layout

## Steps to reproduce

Just go to a lock and ask to see User codes

## Proposed changes

![image](https://user-images.githubusercontent.com/1696899/111869552-651ab380-8980-11eb-947b-db6cc60ac6dc.png)

User Codes are seen as pair Status/Code, but the layout is three columns. Wouldn't it be easier to read pairs in two columns layout, or at least to have a local menu enabling to have a two column layout. 

![image](https://user-images.githubusercontent.com/1696899/111869742-0f92d680-8981-11eb-976a-29e660934b46.png)

**Comment by frenck** [comment]
Hi there,

Thanks for opening an issue, however, this is an add-on. Add-ons wrap existing applications for ease of use. In this case: Z-Wave JS to MQTT.

Please report your feature request with the upstream Z-Wave JS to MQTT project. If it gets implemented, it will become available in the add-on as well.
