### ISSUE TITLE
Can this PR be pulled into update?

### ISSUE THREAD

**Issue by smwoodward** [hassio-addons/addon-zwavejs2mqtt#98]
There is a bug in zwave js that fixes an issue with some inovelli light switches. Can this be pulled into this plugin also? https://github.com/zwave-js/node-zwave-js/pull/2167

**Comment by frenck** [comment]
The addon follows upstream releases.

**Comment by AlCalzone** [comment]
I'll be releasing 7.0.1 this weekend
